
const firebaseConfig={apiKey:"AIzaSyBhTei4lKsyllSKfQo4ubmORQZdgSIeFY0",authDomain:"vendaspiaget.firebaseapp.com",projectId:"vendaspiaget",storageBucket:"vendaspiaget.firebasestorage.app",messagingSenderId:"894187489119",appId:"1:894187489119:web:0b735734579790827bd8ea",measurementId:"G-5CGC7HV4LT"};
firebase.initializeApp(firebaseConfig);const db=firebase.firestore();const auth=firebase.auth();
const FIELD=firebase.firestore.FieldValue;
const EMBEDDED_STUDENTS=[]; /* Base de alunos não é mais embarcada no frontend. A Gestão prepara a fotografia oficial 2026 pela API de implantação. */
const INITIAL_PRODUCTS=[
{id:'refri',nome:'Refrigerante',categoria:'Bebidas geladas',precoCentavos:300,ativo:true,vendaRapida:true,portal:true,controleCapacidade:false},
{id:'suco_copo',nome:'Suco copo',categoria:'Bebidas geladas',precoCentavos:200,ativo:true,vendaRapida:true,portal:true,controleCapacidade:false},
{id:'nescau',nome:'Nescau',categoria:'Bebidas geladas',precoCentavos:300,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'suco_caixa',nome:'Suco caixa',categoria:'Bebidas geladas',precoCentavos:300,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'salgado',nome:'Salgado',categoria:'Lanches',precoCentavos:600,ativo:true,vendaRapida:true,portal:true,controleCapacidade:true,quantidadePadraoDiaria:30},
{id:'torresmo',nome:'Torresmo',categoria:'Lanches',precoCentavos:450,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'biscoito_wafer',nome:'Biscoito wafer',categoria:'Lanches',precoCentavos:300,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'biscoito_pequeno',nome:'Biscoito pequeno',categoria:'Lanches',precoCentavos:200,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'biscoito_grande',nome:'Biscoito grande',categoria:'Lanches',precoCentavos:300,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'petisco',nome:'Petisco',categoria:'Lanches',precoCentavos:200,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'brigadeiro',nome:'Brigadeiro',categoria:'Doces e balas',precoCentavos:250,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'cocada',nome:'Cocada',categoria:'Doces e balas',precoCentavos:250,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'bubbaloo_croc_push',nome:'Bubbaloo / Croc / Push / Plutonita',categoria:'Doces e balas',precoCentavos:50,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'icekiss',nome:'Icekiss',categoria:'Doces e balas',precoCentavos:150,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'pirulito_grande',nome:'Pirulito grande',categoria:'Doces e balas',precoCentavos:150,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'pirulito_pequeno',nome:'Pirulito pequeno',categoria:'Doces e balas',precoCentavos:100,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'plutonita',nome:'Plutonita',categoria:'Doces e balas',precoCentavos:50,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'fini_dori_gigante',nome:'Fini / Dori gigante',categoria:'Doces e balas',precoCentavos:250,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'fini_dori_pequeno',nome:'Fini / Dori pequeno',categoria:'Doces e balas',precoCentavos:150,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'tortuguita',nome:'Tortuguita',categoria:'Doces e balas',precoCentavos:200,ativo:false,vendaRapida:false,portal:false,controleCapacidade:false,motivoInativo:'Estoque zerado / sem reposição'},
{id:'bis',nome:'Bis',categoria:'Doces e balas',precoCentavos:100,ativo:true,vendaRapida:false,portal:true,controleCapacidade:false},
{id:'combo_suco',nome:'Lanche completo com suco',categoria:'Atalhos',ativo:true,vendaRapida:true,portal:true,combo:true,componentes:[{produtoId:'salgado',quantidade:1},{produtoId:'suco_copo',quantidade:1}]},
{id:'combo_refri',nome:'Lanche completo com refrigerante',categoria:'Atalhos',ativo:true,vendaRapida:true,portal:true,combo:true,componentes:[{produtoId:'salgado',quantidade:1},{produtoId:'refri',quantidade:1}]}
];
const INITIAL_USERS=[
{id:'ruan',nome:'Ruan de Jesus',perfil:'cantina',turnos:['manha','tarde'],ativo:true},
{id:'daniele',nome:'Daniele',perfil:'secretaria',turnos:['manha'],ativo:true},
{id:'evanda',nome:'Evanda',perfil:'secretaria',turnos:['tarde'],ativo:true},
{id:'lucas',nome:'Lucas',perfil:'gestao',turnos:['manha','tarde'],ativo:true}
];
const state={user:null,students:[],products:[],config:null,currentPage:'dashboard',selectedStudent:null,cart:[],parentStudent:null,parentChallenge:null,recessGroup:'',currentCash:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(c){return (Number(c||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function parseBRL(v){let s=String(v||'').replace(/[^0-9,.-]/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return Math.round((Number(s)||0)*100)}
function nowIso(){return new Date().toISOString()}function dateKey(d=new Date()){const x=new Date(d);return [x.getFullYear(),String(x.getMonth()+1).padStart(2,'0'),String(x.getDate()).padStart(2,'0')].join('-')}
function humanDate(v){if(!v)return'-';const d=v.toDate?v.toDate():new Date(v);return d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function initials(name){const a=String(name||'').trim().split(/\s+/).filter(Boolean).map(x=>x[0].toUpperCase());return a.length?a.join('. ')+'.':''}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function setConnection(text,ok=true){const el=$('#connectionPill');if(!el)return;el.textContent=text;el.style.background=ok?'rgba(255,255,255,.14)':'rgba(199,46,46,.75)';if(state.parentStudent&&!state.user)el.classList.add('hidden')}
function show(id){['bootScreen','roleScreen','parentScreen','appShell'].forEach(x=>$('#'+x)?.classList.add('hidden'));$('#'+id)?.classList.remove('hidden')}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalBack').classList.add('open')}
function closeModal(){$('#modalBack').classList.remove('open')}
async function seedDatabase(){const status=$('#seedStatus');status.textContent='Preparando os dados...';try{const existing=await db.collection('configuracoes').doc('sistema').get();if(existing.exists){toast('A base já foi inicializada.');await boot();return}const batch=db.batch();const now=nowIso();batch.set(db.collection('configuracoes').doc('sistema'),{nome:'Vendas Piaget',versao:'1.6.0-rc2.7.33',limiteMaximoFiadoCentavos:5000,quantidadePadraoSalgados:30,recreios:{manha_1:{inicio:'09:00',fim:'09:30',turmas:['Infantil 3','Infantil 4','Infantil 5','1º ano','2º ano']},manha_2:{inicio:'09:30',fim:'10:00',turmas:['3º ano','4º ano','5º ano']},tarde:{inicio:'15:30',fim:'16:00',turmas:['6º ano','7º ano','8º ano','9º ano']}},diasSemAula:[],criadoEm:now,atualizadoEm:now});
for(const u of INITIAL_USERS)batch.set(db.collection('usuarios_provisorios').doc(u.id),{...u,criadoEm:now});
const turmas=[...new Map(EMBEDDED_STUDENTS.map(a=>[a.turmaId,{id:a.turmaId,nome:a.turma,ordem:a.ordemTurma,turno:a.turno,grupoRecreio:a.grupoRecreio,recreioInicio:a.recreioInicio,recreioFim:a.recreioFim,anoLetivo:2026}])).values()];for(const t of turmas)batch.set(db.collection('turmas').doc(t.id),t);
for(const p of INITIAL_PRODUCTS)batch.set(db.collection('produtos').doc(p.id),{...p,historicoPrecos:p.precoCentavos?[{precoCentavos:p.precoCentavos,inicioEm:now,usuario:'configuracao_inicial'}]:[],criadoEm:now,atualizadoEm:now});
for(const a of EMBEDDED_STUDENTS){batch.set(db.collection('alunos').doc(a.id),{...a,criadoEm:now,atualizadoEm:now});batch.set(financialAccountRefV167(a.id),{alunoId:a.id,saldoCreditoCentavos:0,dividaCentavos:0,autorizadoSemSaldo:false,limiteFiadoCentavos:0,bloqueioManual:false,bloqueadoPorLimite:false,criadoEm:now,atualizadoEm:now})}
status.textContent=`Importando ${EMBEDDED_STUDENTS.length} alunos e cadastros iniciais...`;await batch.commit();status.textContent='Base inicializada com sucesso.';toast('Dados reais importados.');await boot()}catch(e){console.error(e);status.textContent='Erro: '+e.message}}
function productById(id){return state.products.find(p=>p.id===id)}
function productPrice(p){if(!p)return 0;if(!p.combo)return Number(p.precoCentavos||0);return (p.componentes||[]).reduce((s,c)=>s+productPrice(productById(c.produtoId))*Number(c.quantidade||1),0)}
function productComponents(p,qty=1){if(!p.combo)return[{produtoId:p.id,nome:p.nome,quantidade:qty,precoUnitarioCentavos:productPrice(p)}];return p.componentes.map(c=>{const cp=productById(c.produtoId);return{produtoId:cp.id,nome:cp.nome,quantidade:Number(c.quantidade||1)*qty,precoUnitarioCentavos:productPrice(cp)}})}
function pageHeader(title,sub,actions=''){return `<div class="header"><div><div class="accent"></div><h2 class="title">${esc(title)}</h2><p class="subtitle">${esc(sub)}</p></div><div class="actions">${actions}</div></div>`}

function infoButton(title,text,label='Mais informações'){
  return `<span class="piaget-info-trigger" role="button" tabindex="0" aria-label="${esc(label)}" data-info-title="${esc(title)}" data-info-text="${esc(text)}" onclick="event.preventDefault();event.stopPropagation();showInfoPopover(this)" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();showInfoPopover(this)}">i</span>`;
}
function ensureInfoPopover(){
  let back=document.getElementById('piagetInfoBack');
  if(back)return back;
  back=document.createElement('div');back.id='piagetInfoBack';back.className='piaget-info-back';back.setAttribute('aria-hidden','true');
  back.innerHTML='<section class="piaget-info-popover" role="dialog" aria-modal="true" aria-labelledby="piagetInfoTitle"><header><strong id="piagetInfoTitle">Informação</strong><button type="button" aria-label="Fechar" onclick="closeInfoPopover()">×</button></header><div id="piagetInfoText"></div></section>';
  back.addEventListener('click',event=>{if(event.target===back)closeInfoPopover()});document.body.appendChild(back);return back;
}
function showInfoPopover(trigger){
  const back=ensureInfoPopover(),title=trigger?.dataset?.infoTitle||'Informação',text=trigger?.dataset?.infoText||'';
  document.getElementById('piagetInfoTitle').textContent=title;document.getElementById('piagetInfoText').textContent=text;
  back.classList.add('open');back.setAttribute('aria-hidden','false');document.body.classList.add('piaget-info-open');
  setTimeout(()=>back.querySelector('button')?.focus(),0);
}
function closeInfoPopover(){const back=document.getElementById('piagetInfoBack');if(!back)return;back.classList.remove('open');back.setAttribute('aria-hidden','true');document.body.classList.remove('piaget-info-open')}
window.infoButton=infoButton;window.showInfoPopover=showInfoPopover;window.closeInfoPopover=closeInfoPopover;
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeInfoPopover()});

function currentGroup(){const now=new Date(),m=now.getHours()*60+now.getMinutes();if(m>=540&&m<=570)return'manha_1';if(m>570&&m<=600)return'manha_2';if(m>=930&&m<=960)return'tarde';return state.recessGroup||'manha_1'}
function renderAtendimento(){state.recessGroup=currentGroup();const groups=state.config.recreios;$('#mainContent').innerHTML=pageHeader('Atendimento da cantina','Venda em dinheiro, lançamento na conta e atalhos rápidos.')+`<div class="grid g2"><div><div class="card"><div class="card-head"><div class="card-title">Venda rápida em dinheiro</div><span class="badge b-green">Sem identificar aluno</span></div><div class="card-body"><div class="fg"><label>Recreio em atendimento</label><select class="fi" id="recessSelect" onchange="state.recessGroup=this.value"><option value="manha_1" ${state.recessGroup==='manha_1'?'selected':''}>9h às 9h30 — Infantil 3 ao 2º ano</option><option value="manha_2" ${state.recessGroup==='manha_2'?'selected':''}>9h30 às 10h — 3º ao 5º ano</option><option value="tarde" ${state.recessGroup==='tarde'?'selected':''}>15h30 às 16h — 6º ao 9º ano</option></select></div><div class="product-grid" id="quickProducts"></div><div id="cashCart" style="margin-top:14px"></div></div></div></div><div><div class="card"><div class="card-head"><div class="card-title">Lançar na conta do aluno</div><span class="badge b-blue">Saldo ou fiado</span></div><div class="card-body"><div class="fg"><label>Pesquisar nome ou matrícula</label><input class="fi" id="cantinaStudentSearch" placeholder="Digite pelo menos 2 letras" oninput="searchStudentsInto(this.value,'cantinaStudentResults','openStudentAccountSale')"></div><div id="cantinaStudentResults" class="search-results"></div></div></div></div></div>`;renderQuickProducts();renderCashCart()}
function renderCashCart(){const el=$('#cashCart');if(!el)return;const total=state.cart.reduce((s,x)=>s+x.precoUnitarioCentavos*x.quantidade,0);el.innerHTML=state.cart.length?`<div class="card" style="box-shadow:none"><div class="card-body">${state.cart.map((x,i)=>`<div class="cart-item"><div><strong>${esc(x.nome)}</strong><div class="muted">${x.quantidade} × ${fmt(x.precoUnitarioCentavos)}</div></div><div class="actions"><strong>${fmt(x.precoUnitarioCentavos*x.quantidade)}</strong><button class="btn btn-outline" onclick="state.cart.splice(${i},1);renderCashCart()">Remover</button></div></div>`).join('')}<div class="cart-item"><strong>Total</strong><strong>${fmt(total)}</strong></div><button class="btn btn-green" style="width:100%;margin-top:10px" onclick="registerCashSale()">Confirmar venda em dinheiro</button></div></div>`:`<div class="empty" style="padding:17px">Toque nos produtos para montar a venda.</div>`}
async function ensureCashSession(point){const shift=state.recessGroup==='tarde'?'tarde':'manha';const id=`${point}_${dateKey()}_${shift}`;const ref=db.collection('caixas').doc(id);const snap=await ref.get();if(snap.exists&&snap.data().status==='aberto')return{id,...snap.data()};const initial=point==='cantina'?1000:0;await ref.set({id,ponto:point,turno:shift,dataChave:dateKey(),operadorId:state.user.id,operadorNome:state.user.nome,valorInicialCentavos:initial,status:'aberto',abertoEm:nowIso(),atualizadoEm:nowIso()},{merge:true});await db.collection('movimentos_caixa').add({caixaId:id,tipo:'suprimento_inicial',valorCentavos:initial,origem:point==='cantina'?'secretaria':'abertura',destino:point,usuarioId:state.user.id,dataChave:dateKey(),criadoEm:nowIso()});return{id,ponto:point,turno:shift,valorInicialCentavos:initial,status:'aberto'}}
function expandCart(cart){const map={};for(const line of cart){const p=productById(line.produtoId);for(const c of productComponents(p,line.quantidade)){if(!map[c.produtoId])map[c.produtoId]={...c};else map[c.produtoId].quantidade+=c.quantidade}}return Object.values(map)}
function activeReservationTotal(map){const now=Date.now();return Object.values(map||{}).reduce((sum,r)=>new Date(r.expiraEm||0).getTime()>now?sum+Number(r.quantidade||0):sum,0)}
function searchStudentsInto(term,target,callback){const el=$('#'+target);const q=String(term||'').trim().toLowerCase();if(q.length<2){el.innerHTML='';return}const found=state.students.filter(a=>a.nome.toLowerCase().includes(q)||a.matricula.includes(q)).slice(0,30);el.innerHTML=found.length?found.map(a=>`<div class="student-row" onclick="${callback}('${a.id}')"><div><strong>${esc(a.nome)}</strong><div class="muted">${esc(a.turma)} · Matrícula ${esc(a.matricula)}</div></div><span>›</span></div>`).join(''):'<div class="empty">Nenhum aluno encontrado.</div>'}
async function openStudentAccountSale(id){const a=state.students.find(x=>x.id===id),account=await getAccount(id);state.selectedStudent=a;state.cart=[];openModal('Lançar na conta do aluno',`<div class="status-panel"><div class="small">${esc(a.turma)} · Matrícula ${esc(a.matricula)}</div><div class="big">${esc(a.nome)}</div><div style="margin-top:9px">Saldo ${fmt(account.saldoCreditoCentavos)} · Dívida ${fmt(account.dividaCentavos)} · Limite ${fmt(account.limiteFiadoCentavos)}</div></div><div id="accountPermission" style="margin:12px 0">${accountStatusHtml(account)}</div><div class="product-grid">${state.products.filter(p=>p.ativo).map(p=>`<button class="product-btn" onclick="addAccountProduct('${p.id}')"><strong>${esc(p.nome)}</strong><span>${fmt(productPrice(p))}</span></button>`).join('')}</div><div style="margin-top:12px" id="accountCart"></div>`);renderAccountCart(account)}
function accountStatusHtml(a){const available=Math.max(0,Number(a.limiteFiadoCentavos||0)-Number(a.dividaCentavos||0));const blocked=a.bloqueioManual||(!a.autorizadoSemSaldo&&Number(a.saldoCreditoCentavos||0)<=0)||a.bloqueadoPorLimite;return `<div class="alert ${blocked?'danger':''}"><strong>${blocked?'Restrito':'Liberado'}</strong><br>Crédito pré-pago: ${fmt(a.saldoCreditoCentavos)} · Espaço no limite: ${fmt(available)}${a.bloqueioManual?'<br>Bloqueio manual ativo.':''}</div>`}
function addAccountProduct(id){const p=productById(id),f=state.cart.find(x=>x.produtoId===id);if(f)f.quantidade++;else state.cart.push({produtoId:id,nome:p.nome,quantidade:1,precoUnitarioCentavos:productPrice(p)});getAccount(state.selectedStudent.id).then(renderAccountCart)}
function renderAccountCart(account){const el=$('#accountCart');if(!el)return;const total=state.cart.reduce((s,x)=>s+x.quantidade*x.precoUnitarioCentavos,0);el.innerHTML=state.cart.length?`${state.cart.map((x,i)=>`<div class="cart-item"><span>${x.quantidade} × ${esc(x.nome)}</span><span><strong>${fmt(x.quantidade*x.precoUnitarioCentavos)}</strong> <button class="btn btn-outline" onclick="state.cart.splice(${i},1);getAccount(state.selectedStudent.id).then(renderAccountCart)">×</button></span></div>`).join('')}<div class="cart-item"><strong>Total</strong><strong>${fmt(total)}</strong></div><button class="btn btn-primary" style="width:100%;margin-top:10px" onclick="registerAccountConsumption()">Confirmar na conta</button>`:'<div class="empty" style="padding:14px">Selecione os produtos.</div>'}
async function getAccount(id){const s=await financialAccountRefV167(id).get();return s.exists?s.data():{alunoId:id,saldoCreditoCentavos:0,dividaCentavos:0,autorizadoSemSaldo:false,limiteFiadoCentavos:0,bloqueioManual:false,bloqueadoPorLimite:false}}
async function renderEntregas(){const el=$('#mainContent');el.innerHTML=pageHeader('Pedidos do dia','Entregas antecipadas e ocorrências por aluno.')+'<div class="empty">Carregando...</div>';const snap=await db.collection('ocorrencias_entrega').where('dataChave','==',dateKey()).limit(300).get().catch(()=>({docs:[]}));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.turma||'').localeCompare(b.turma||'')||(a.alunoNome||'').localeCompare(b.alunoNome||''));el.innerHTML=pageHeader('Pedidos do dia','Entregas antecipadas e ocorrências por aluno.')+`<div class="card"><div class="card-head"><div class="card-title">Hoje — ${new Date().toLocaleDateString('pt-BR')}</div><span class="badge b-blue">${rows.length} ocorrências</span></div>${rows.length?`<div class="table-wrap" style="border:0;border-radius:0"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Itens</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.alunoNome)}</strong></td><td>${esc(r.turma)}</td><td>${(r.itens||[]).map(x=>`${x.quantidade}× ${esc(x.nome)}`).join('<br>')}</td><td><span class="badge ${r.status==='entregue'?'b-green':r.status==='ausente'?'b-yellow':'b-blue'}">${esc(r.status)}</span></td><td><div class="actions"><button class="btn btn-green" onclick="setOccurrence('${r.id}','entregue')">Entregue</button><button class="btn btn-outline" onclick="setOccurrence('${r.id}','ausente')">Ausente</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum pedido programado para hoje.</div>'}</div>`}
async function setOccurrence(id,status){const ref=db.collection('ocorrencias_entrega').doc(id);const snap=await ref.get();if(!snap.exists)return;const o=snap.data();if(status==='ausente'&&o.status!=='ausente'){const value=(o.itens||[]).reduce((s,x)=>s+x.quantidade*x.precoUnitarioCentavos,0);const acc=financialAccountRefV167(o.alunoId);const mov=db.collection('movimentos_conta').doc();await db.runTransaction(async tx=>{const as=await tx.get(acc),a=as.data()||{};tx.set(acc,{saldoCreditoCentavos:Number(a.saldoCreditoCentavos||0)+value,atualizadoEm:nowIso()},{merge:true});tx.set(mov,{id:mov.id,alunoId:o.alunoId,tipo:'credito_ausencia',valorCentavos:value,pedidoId:o.pedidoId,ocorrenciaId:id,origem:'pedido_pago_nao_entregue',usuarioId:state.user.id,dataChave:dateKey(),criadoEm:nowIso()});tx.set(ref,{status:'ausente',creditadoCentavos:value,atualizadoEm:nowIso(),alteradoPor:state.user.id},{merge:true})});await releaseSalgadoFromOccurrence(o)}else await ref.set({status,atualizadoEm:nowIso(),alteradoPor:state.user.id},{merge:true});await audit('ocorrencia_'+status,{ocorrenciaId:id,alunoId:o.alunoId});renderEntregas();toast('Situação atualizada.')}
async function releaseSalgadoFromOccurrence(o){const q=(o.itens||[]).filter(x=>x.produtoId==='salgado').reduce((s,x)=>s+x.quantidade,0);if(!q)return;const ref=db.collection('disponibilidade_salgados').doc(o.dataChave);await db.runTransaction(async tx=>{const s=await tx.get(ref),d=s.data()||{};tx.set(ref,{pedidosConfirmados:Math.max(0,Number(d.pedidosConfirmados||0)-q),liberadoPorAusencia:Number(d.liberadoPorAusencia||0)+q,atualizadoEm:nowIso()},{merge:true})})}
function renderConsulta(){renderStudentSearchPage('Consultar aluno','Pesquise para ver conta, autorização, saldo, dívida e histórico.')}
function renderAlunos(){renderStudentSearchPage('Alunos e contas','Consulta completa e administração da conta do aluno.')}
function renderStudentSearchPage(title,sub){$('#mainContent').innerHTML=pageHeader(title,sub)+`<div class="card"><div class="card-body"><div class="fg"><label>Nome ou matrícula</label><input class="fi" placeholder="Pesquisar aluno" oninput="searchStudentsInto(this.value,'genericStudentResults','openStudentDetails')"></div><div id="genericStudentResults" class="search-results"></div></div></div>`}
async function openStudentDetails(id){const a=state.students.find(x=>x.id===id),acc=await getAccount(id);const ms=await db.collection('movimentos_conta').where('alunoId','==',id).limit(250).get();const moves=ms.docs.map(d=>({id:d.id,...d.data()})).sort((x,y)=>String(y.criadoEm).localeCompare(String(x.criadoEm))).slice(0,50);const canManage=state.user&&['secretaria','gestao'].includes(state.user.perfil);openModal('Conta do aluno',`<div class="status-panel"><div class="small">${esc(a.turma)} · Matrícula ${esc(a.matricula)}</div><div class="big">${esc(a.nome)}</div><div class="small">Responsável: ${esc(a.responsavelFinanceiro)}</div></div><div class="grid g3" style="margin:12px 0"><div class="kpi green"><div class="kpi-label">Crédito</div><div class="kpi-value">${fmt(acc.saldoCreditoCentavos)}</div></div><div class="kpi orange"><div class="kpi-label">Dívida</div><div class="kpi-value">${fmt(acc.dividaCentavos)}</div></div><div class="kpi"><div class="kpi-label">Limite</div><div class="kpi-value">${fmt(acc.limiteFiadoCentavos)}</div></div></div><div class="switch-line"><div><strong>Compra sem saldo</strong><div class="muted">${acc.autorizadoSemSaldo?'Autorizada pelo responsável':'Bloqueada pelo responsável'}</div></div><span class="badge ${acc.autorizadoSemSaldo?'b-green':'b-red'}">${acc.autorizadoSemSaldo?'liberada':'bloqueada'}</span></div>${canManage?`<div class="actions" style="margin:12px 0"><button class="btn btn-outline" onclick="toggleManualBlock('${id}',${!acc.bloqueioManual})">${acc.bloqueioManual?'Remover bloqueio manual':'Bloquear conta'}</button><button class="btn btn-light" onclick="registerManualPayment('${id}')">Registrar pagamento</button><button class="btn btn-primary" onclick="generateReport('${id}')">Relatório PDF / imagem</button></div>`:''}<div class="card-title" style="margin:15px 0 8px">Movimentos recentes</div>${moves.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Detalhes</th><th style="text-align:right">Valor</th></tr></thead><tbody>${moves.map(m=>`<tr><td>${humanDate(m.criadoEm)}</td><td>${esc(m.tipo)}</td><td>${(m.itens||[]).map(x=>`${x.quantidade}× ${esc(x.nome)}`).join(', ')||'-'}</td><td class="money">${fmt(m.valorCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem movimentos.</div>'}`)}
async function toggleManualBlock(id,val){const patch=val?{bloqueioManual:true}:{bloqueioManual:false,bloqueadoPorLimite:false,bloqueioSaldoSemanal:false};await financialAccountRefV167(id).set({...patch,atualizadoEm:nowIso()},{merge:true});await audit(val?'bloqueio_manual':'desbloqueio_manual',{alunoId:id});closeModal();toast(val?'Conta bloqueada.':'Conta desbloqueada.')}
function registerManualPayment(id){openModal('Registrar pagamento',`<div class="fg"><label>Valor recebido</label><input id="manualPayAmount" class="fi" placeholder="0,00"></div><div class="fg"><label>Forma</label><select id="manualPayMethod" class="fi"><option value="dinheiro">Dinheiro</option><option value="pix_banco">Pix banco</option><option value="pix_rede">Pix Rede / Laranjinha</option><option value="cartao_rede">Cartão Rede / Laranjinha</option><option value="infinitepay">InfinitePay</option></select></div><button class="btn btn-green" style="width:100%" onclick="saveManualPayment('${id}')">Confirmar recebimento</button>`)}
async function saveManualPayment(id){const amount=parseBRL($('#manualPayAmount').value);if(amount<=0)return appMessage('Informe o valor.');const method=$('#manualPayMethod').value,accRef=financialAccountRefV167(id),move=db.collection('movimentos_conta').doc(),pay=db.collection('pagamentos').doc();await db.runTransaction(async tx=>{const s=await tx.get(accRef),a=s.data()||{};const debt=Number(a.dividaCentavos||0),applied=Math.min(debt,amount),credit=amount-applied;tx.set(accRef,{dividaCentavos:debt-applied,saldoCreditoCentavos:Number(a.saldoCreditoCentavos||0)+credit,bloqueadoPorLimite:(Number(a.limiteFiadoCentavos||0)>0&&(debt-applied)>=Number(a.limiteFiadoCentavos||0)),atualizadoEm:nowIso()},{merge:true});tx.set(move,{id:move.id,alunoId:id,tipo:'pagamento',valorCentavos:amount,aplicadoDividaCentavos:applied,creditoGeradoCentavos:credit,formaPagamento:method,usuarioId:state.user.id,dataChave:dateKey(),criadoEm:nowIso()});tx.set(pay,{id:pay.id,alunoId:id,valorBrutoCentavos:amount,formaPagamento:method,status:'confirmado',origem:'secretaria',usuarioId:state.user.id,dataChave:dateKey(),criadoEm:nowIso()})});await audit('pagamento_manual',{alunoId:id,valorCentavos:amount,forma:method});closeModal();toast('Pagamento registrado.')}
function chooseSaleStudent(id){const a=state.students.find(x=>x.id===id);$('#saleStudentId').value=id;$('#saleStudentText').value=`${a.nome} — ${a.turma}`;$('#saleStudentResults').innerHTML=''}
function addToManualCart(id){const p=productById(id),f=state.cart.find(x=>x.produtoId===id);if(f)f.quantidade++;else state.cart.push({produtoId:id,nome:p.nome,quantidade:1,precoUnitarioCentavos:productPrice(p)});renderManualCart()}
function renderManualCart(){const el=$('#manualCart');if(!el)return;const total=state.cart.reduce((s,x)=>s+x.quantidade*x.precoUnitarioCentavos,0);el.innerHTML=state.cart.length?`${state.cart.map((x,i)=>`<div class="cart-item"><span>${x.quantidade}× ${esc(x.nome)}</span><span>${fmt(x.quantidade*x.precoUnitarioCentavos)} <button class="btn btn-outline" onclick="state.cart.splice(${i},1);renderManualCart()">×</button></span></div>`).join('')}<div class="cart-item"><strong>Total</strong><strong>${fmt(total)}</strong></div><button class="btn btn-primary" style="width:100%;margin-top:10px" onclick="saveManualSale()">Registrar venda bruta</button>`:'<div class="empty" style="padding:14px">Selecione os produtos.</div>'}
async function saveManualSale(){if(!state.cart.length)return;const items=expandCart(state.cart),total=items.reduce((s,x)=>s+x.quantidade*x.precoUnitarioCentavos,0),studentId=$('#saleStudentId').value||null,method=$('#manualSaleMethod').value;try{let cash=null;if(method==='dinheiro')cash=await ensureCashSession('secretaria');const sale=db.collection('vendas').doc(),mov=cash?db.collection('movimentos_caixa').doc():null,iq=db.collection('fila_integracao').doc();await db.runTransaction(async tx=>{const stock=await readSalgadoUpdateTx(tx,items,'venda_dinheiro');if(stock)tx.set(stock.ref,stock.data,{merge:true});tx.set(sale,{id:sale.id,alunoId:studentId,origem:'secretaria',operadorId:state.user.id,operadorNome:state.user.nome,formaPagamento:method,valorBrutoCentavos:total,itens:items,caixaId:cash?.id||null,dataChave:dateKey(),criadoEm:nowIso(),status:'confirmada'});if(mov)tx.set(mov,{id:mov.id,caixaId:cash.id,tipo:'venda',vendaId:sale.id,valorCentavos:total,usuarioId:state.user.id,dataChave:dateKey(),criadoEm:nowIso()});tx.set(iq,{id:iq.id,tipo:'venda_bruta',origem:'secretaria',sourceId:sale.id,valorBrutoCentavos:total,formaPagamento:method,status:'pendente',dataChave:dateKey(),criadoEm:nowIso()})});await audit('venda_manual',{vendaId:sale.id,valorCentavos:total,forma:method});state.cart=[];renderManualCart();toast('Venda bruta registrada.')}catch(e){appMessage(e.message)}}
async function renderCobrancas(){const el=$('#mainContent');el.innerHTML=pageHeader('Cobranças','Contas em aberto, fechamento semanal e relatórios.')+'<div class="empty">Carregando...</div>';const snap=await financialAccountsSnapshotV167();const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Number(x.dividaCentavos||0)>0).sort((a,b)=>b.dividaCentavos-a.dividaCentavos);el.innerHTML=pageHeader('Cobranças','Contas em aberto, fechamento semanal e relatórios.',`<button class="btn btn-orange" onclick="weeklyClose()">Gerar fechamento da semana</button>`)+`<div class="card"><div class="card-head"><div class="card-title">Alunos com dívida</div><span class="badge b-yellow">${rows.length}</span></div>${rows.length?`<div class="table-wrap" style="border:0;border-radius:0"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Autorização</th><th>Limite</th><th style="text-align:right">Em aberto</th><th>Ações</th></tr></thead><tbody>${rows.map(r=>{const a=state.students.find(x=>x.id===r.id)||{};return`<tr><td><strong>${esc(a.nome||r.id)}</strong></td><td>${esc(a.turma||'-')}</td><td><span class="badge ${r.autorizadoSemSaldo?'b-green':'b-red'}">${r.autorizadoSemSaldo?'liberada':'bloqueada'}</span></td><td>${fmt(r.limiteFiadoCentavos)}</td><td class="money">${fmt(r.dividaCentavos)}</td><td><div class="actions"><button class="btn btn-primary" onclick="generateReport('${r.id}')">PDF / imagem</button><button class="btn btn-light" onclick="copyParentLink('${r.id}')">Copiar link</button></div></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma conta em aberto.</div>'}</div>`}
async function weeklyClose(){const shift=state.user.turnos?.includes('tarde')&&state.user.turnos?.length===1?'tarde':state.user.turnos?.includes('manha')&&state.user.turnos?.length===1?'manha':'todos';await db.collection('fechamentos_semanais').add({dataChave:dateKey(),turno:shift,usuarioId:state.user.id,criadoEm:nowIso()});await audit('fechamento_semanal',{turno:shift});toast('Fechamento semanal registrado. Os relatórios já podem ser gerados.')}
async function copyParentLink(id){const a=state.students.find(x=>x.id===id);await navigator.clipboard.writeText(parentUrl(a));toast('Link copiado.')}
function computeOpenDebtLines(moves){const sorted=[...moves].sort((a,b)=>String(a.criadoEm).localeCompare(String(b.criadoEm))),queue=[];for(const m of sorted){if(m.tipo==='consumo'&&Number(m.dividaGeradaCentavos||0)>0)queue.push({...m,abertoCentavos:Number(m.dividaGeradaCentavos||0)});const paid=Number(m.aplicadoDividaCentavos||0);if(paid>0){let left=paid;for(const q of queue){const use=Math.min(left,q.abertoCentavos);q.abertoCentavos-=use;left-=use;if(left<=0)break}}}return queue.filter(x=>x.abertoCentavos>0)}
async function renderPedidos(){const el=$('#mainContent');el.innerHTML=pageHeader('Pedidos','Pedidos antecipados e acompanhamento de pagamento e entrega.')+'<div class="empty">Carregando...</div>';const snap=await db.collection('pedidos').orderBy('criadoEm','desc').limit(150).get().catch(()=>db.collection('pedidos').limit(150).get()).catch(()=>({docs:[]}));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm))).slice(0,200);el.innerHTML=pageHeader('Pedidos','Pedidos antecipados e acompanhamento de pagamento e entrega.')+`<div class="card">${rows.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Data</th><th>Aluno</th><th>Tipo</th><th>Pagamento</th><th>Entrega</th><th style="text-align:right">Total</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${humanDate(r.criadoEm)}</td><td><strong>${esc(r.alunoNome)}</strong><br><span class="muted">${esc(r.turma)}</span></td><td>${esc(r.modalidade)}</td><td><span class="badge ${r.statusPagamento==='pago'?'b-green':'b-yellow'}">${esc(r.statusPagamento)}</span></td><td>${esc(r.statusPedido||'-')}</td><td class="money">${fmt(r.totalCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum pedido ainda.</div>'}</div>`}
async function openCash(point,shift){state.recessGroup=shift==='tarde'?'tarde':'manha_1';await ensureCashSession(point);renderCaixa();toast('Caixa aberto.')}
async function closeCash(id,expected){const counted=parseBRL($('#cashCounted').value);const diff=counted-expected;await db.collection('caixas').doc(id).set({status:'fechado',valorContadoCentavos:counted,valorEsperadoRegistradoCentavos:expected,diferencaCentavos:diff,fechadoEm:nowIso(),atualizadoEm:nowIso()},{merge:true});await db.collection('movimentos_caixa').add({caixaId:id,tipo:'retorno_secretaria',valorCentavos:counted,usuarioId:state.user.id,dataChave:dateKey(),criadoEm:nowIso()});await audit('fechamento_caixa',{caixaId:id,contadoCentavos:counted,diferencaCentavos:diff});renderCaixa();toast('Caixa fechado.')}
function toggleUniformModel(){const s=$('#uniformSize').value,big=['P','M','G','GG','XGG'].includes(s);$('#uniformModel').disabled=!big;if(!big)$('#uniformModel').value=''}
function chooseUniformStudent(id){const a=state.students.find(x=>x.id===id);$('#uniformStudentId').value=id;$('#uniformStudentText').value=`${a.nome} — ${a.turma}`;$('#uniformStudentResults').innerHTML=''}
function editProductPrice(id){const p=productById(id);openModal('Alterar preço',`<p><strong>${esc(p.nome)}</strong></p><div class="fg"><label>Novo preço</label><input id="newProductPrice" class="fi" value="${(productPrice(p)/100).toFixed(2).replace('.',',')}"></div><button class="btn btn-primary" onclick="saveProductPrice('${id}')">Salvar preço</button>`)}
async function saveProductPrice(id){const v=parseBRL($('#newProductPrice').value);if(v<=0)return appMessage('Preço inválido.');const p=productById(id),hist=[...(p.historicoPrecos||[]),{precoCentavos:v,inicioEm:nowIso(),usuario:state.user.id}];await db.collection('produtos').doc(id).set({precoCentavos:v,historicoPrecos:hist,atualizadoEm:nowIso()},{merge:true});await audit('preco_produto',{produtoId:id,precoCentavos:v});await loadCore();closeModal();renderProdutos()}
async function toggleProduct(id,val){await db.collection('produtos').doc(id).set({ativo:val,portal:val,atualizadoEm:nowIso()},{merge:true});await audit(val?'produto_ativado':'produto_inativado',{produtoId:id});await loadCore();renderProdutos()}
function renderConfig(){$('#mainContent').innerHTML=pageHeader('Configurações','Parâmetros operacionais da escola.')+`<div class="grid g2"><div class="card"><div class="card-head"><div class="card-title">Cantina</div></div><div class="card-body"><div class="fg"><label>Teto de fiado da escola</label><input id="cfgLimit" class="fi" value="${(state.config.limiteMaximoFiadoCentavos/100).toFixed(2).replace('.',',')}" disabled></div><div class="fg"><label>Salgados padrão por dia</label><input id="cfgSalgado" type="number" class="fi" value="${state.config.quantidadePadraoSalgados||30}"></div><button class="btn btn-primary" onclick="saveConfig()">Salvar</button></div></div><div class="card"><div class="card-head"><div class="card-title">Camisa de farda</div></div><div class="card-body"><div class="fg"><label>Preço 4 a 14</label><input id="cfgUniformChild" class="fi" value="${((state.config.precoFardaInfantilCentavos||4200)/100).toFixed(2).replace('.',',')}"></div><div class="fg"><label>Preço P a XGG</label><input id="cfgUniformAdult" class="fi" value="${((state.config.precoFardaAdultoCentavos||4700)/100).toFixed(2).replace('.',',')}"></div><button class="btn btn-primary" onclick="saveConfig()">Salvar</button></div></div></div>`}
async function saveConfig(){await db.collection('configuracoes').doc('sistema').set({quantidadePadraoSalgados:Number($('#cfgSalgado')?.value||state.config.quantidadePadraoSalgados),precoFardaInfantilCentavos:parseBRL($('#cfgUniformChild')?.value||42),precoFardaAdultoCentavos:parseBRL($('#cfgUniformAdult')?.value||47),atualizadoEm:nowIso()},{merge:true});await loadCore();toast('Configurações salvas.')}
async function renderAuditoria(){const snap=await db.collection('historico_auditoria').orderBy('criadoEm','desc').limit(150).get().catch(()=>db.collection('historico_auditoria').limit(150).get()).catch(()=>({docs:[]}));const rows=snap.docs.map(d=>d.data()).sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm))).slice(0,300);$('#mainContent').innerHTML=pageHeader('Auditoria','Registro das principais ações do sistema.')+`<div class="card">${rows.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Detalhes</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${humanDate(r.criadoEm)}</td><td>${esc(r.usuarioNome||r.usuarioId||'-')}</td><td><strong>${esc(r.acao)}</strong></td><td class="muted">${esc(JSON.stringify(r.dados||{})).slice(0,180)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem registros.</div>'}</div>`}
async function audit(action,data){try{await db.collection('historico_auditoria').add({acao:action,dados:data||{},usuarioId:state.user?.id||'responsavel',usuarioNome:state.user?.nome||state.parentStudent?.responsavelFinanceiro||'Responsável',criadoEm:nowIso()})}catch(e){console.warn('audit',e)}}
function enterParent(){show('parentScreen');renderParentLogin()}
function randomUnique(arr,count,exclude=[]){const pool=[...new Set(arr.filter(Boolean).filter(x=>!exclude.includes(x)))].sort(()=>Math.random()-.5);return pool.slice(0,count)}
async function parentToggleAuthorization(val){await financialAccountRefV167(state.parentStudent.id).set({autorizadoSemSaldo:val,limiteFiadoCentavos:val?Math.max(0,Math.min(5000,Number($('#parentLimit')?.value||50)*100)):Number((await getAccount(state.parentStudent.id)).limiteFiadoCentavos||0),atualizadoEm:nowIso()},{merge:true});await audit('autorizacao_responsavel',{alunoId:state.parentStudent.id,autorizado:val});renderParentPortal()}
async function saveParentLimit(){const v=Math.max(0,Math.min(50,Number($('#parentLimit').value||0))),acc=await getAccount(state.parentStudent.id),limit=Math.round(v*100);await financialAccountRefV167(state.parentStudent.id).set({limiteFiadoCentavos:limit,bloqueadoPorLimite:limit>0&&Number(acc.dividaCentavos||0)>=limit,atualizadoEm:nowIso()},{merge:true});await audit('limite_responsavel',{alunoId:state.parentStudent.id,limiteCentavos:limit});toast('Limite salvo.');renderParentPortal()}

/* =====================================================================
   V1.1.0 — Venda composta da secretaria, KPIs investigáveis e documentos
   ===================================================================== */
function uidLocal(prefix='id'){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
function centsOfLine(x){return Number(x.valorCentavos ?? ((Number(x.quantidade||1)*Number(x.precoUnitarioCentavos||0)) || 0))}
function saleTotalV110(){return (state.secretariaSale?.cart||[]).reduce((s,x)=>s+centsOfLine(x),0)}
function paymentTotalV110(){return (state.secretariaSale?.payments||[]).reduce((s,x)=>s+Number(x.valorAplicadoCentavos||0),0)}
function remainingSaleV110(){return Math.max(0,saleTotalV110()-paymentTotalV110())}
function ensureSaleStateV110(reset=false){if(reset||!state.secretariaSale)state.secretariaSale={studentId:null,student:null,cart:[],payments:[]};return state.secretariaSale}
function paymentLabelV110(p){if(p.metodo==='dinheiro')return 'Dinheiro';if(p.metodo==='pix')return `Pix · ${String(p.origemPix||'').replaceAll('_',' ')}`;if(p.metodo==='cartao')return `Cartão · ${String(p.adquirente||'').replaceAll('_',' ')} · ${p.modalidadeCartao||''}${p.modalidadeCartao==='credito'?` ${p.parcelas||1}x`:''}`;return p.metodo}
function itemKindLabelV110(x){return x.tipo==='produto'?'Produto':x.tipo==='debito_conta'?'Débito em aberto':x.tipo==='farda'?'Camisa de farda':'Item avulso'}
function studentNameV110(id){return state.students.find(a=>a.id===id)?.nome||'-'}
function saleStudentV110(){return state.secretariaSale?.student||null}


function lunchDefaultActiveV181(day){const d=new Date(String(day)+'T12:00:00');return ![0,6].includes(d.getDay())&&!(state.config?.diasSemAula||[]).includes(day)}
function lunchDayStatusV181(day,d={}){const planned=Math.max(0,Number(d.quantidadePlanejada??state.config?.quantidadePadraoSalgados??30));const receivedDefined=d.quantidadeRecebida!==undefined&&d.quantidadeRecebida!==null&&d.quantidadeRecebida!=='';const received=receivedDefined?Math.max(0,Number(d.quantidadeRecebida||0)):null;const capacity=receivedDefined?received:planned;const active=typeof d.vendaAtiva==='boolean'?d.vendaAtiva:lunchDefaultActiveV181(day);const reservations=activeReservationTotal(d.reservas);const used=Number(d.vendidoDinheiro||0)+Number(d.vendidoAvulso||0)+Number(d.consumoConta||0)+Number(d.pedidosConfirmados||0)+reservations;return{active,planned,received,capacity,used,available:Math.max(0,capacity-used),deficit:Math.max(0,used-capacity)}}
async function readSalgadoUpdateTx(tx,items,kind,day=dateKey()){const q=(items||[]).filter(x=>x.produtoId==='salgado').reduce((s,x)=>s+Number(x.quantidade||0),0);if(!q)return null;const ref=db.collection('disponibilidade_salgados').doc(day),snap=await tx.get(ref);const d=snap.exists?snap.data():{};const info=lunchDayStatusV181(day,d);if(!info.active)throw new Error(`A venda de lanches está desativada em ${day.split('-').reverse().join('/')}.`);if(info.used+q>info.capacity)throw new Error(`Não há salgados suficientes. Disponíveis: ${info.available}.`);const field=kind==='consumo_conta'?'consumoConta':kind==='pedido'?'pedidosConfirmados':kind==='venda_dinheiro'?'vendidoDinheiro':'vendidoAvulso';return{ref,data:{dataChave:day,quantidadePlanejada:info.planned,[field]:Number(d[field]||0)+q,atualizadoEm:nowIso()}}}

async function renderSalesWorkspaceV110(){const st=ensureSaleStateV110();const el=$('#mainContent');el.innerHTML=pageHeader('Vendas da secretaria','Monte uma única operação com lanche, farda, débitos e itens avulsos.',`<button class="btn btn-outline" onclick="renderSalesHistoryV110()">Histórico de vendas</button>`)+`<div class="grid g4" id="salesKpisV110"><div class="kpi"><div class="kpi-label">Hoje</div><div class="kpi-value">...</div></div></div><div class="sales-shell" style="margin-top:14px"><div class="sales-panel"><div class="card"><div class="card-head"><div class="card-title"><span class="step-badge">1</span>Aluno da operação</div><button class="btn btn-outline" onclick="clearSaleStudentV110()">Venda sem aluno</button></div><div class="card-body"><div class="fg"><label>Nome ou matrícula</label><input id="saleV110StudentSearch" class="fi" placeholder="Pesquise o aluno" oninput="searchStudentsInto(this.value,'saleV110StudentResults','chooseSaleStudentV110')"></div><div id="saleV110StudentResults" class="search-results"></div><div id="saleV110StudentChip"></div></div></div><div class="card"><div class="card-head"><div class="card-title"><span class="step-badge">2</span>Itens da venda</div></div><div class="card-body"><div class="sale-toolbar"><button class="btn btn-light" onclick="openCatalogPickerV110()">+ Produto cadastrado</button><button class="btn btn-light" onclick="addDebtItemV110()">+ Débito em aberto</button><button class="btn btn-light" onclick="openUniformItemV110()">+ Camisa de farda</button><button class="btn btn-light" onclick="openFreeItemV110()">+ Item avulso</button></div><p class="section-note">O carrinho pode misturar categorias na mesma operação. Cada item manterá sua própria classificação.</p><div id="saleV110Cart"></div></div></div></div><div class="sales-panel"><div class="card"><div class="card-head"><div class="card-title"><span class="step-badge">3</span>Pagamento</div><span class="badge b-blue">Bruto</span></div><div class="card-body"><div id="saleV110Payments"></div><button class="btn btn-light" style="width:100%;margin-top:10px" onclick="openPaymentV110()">+ Adicionar forma de pagamento</button></div></div><div class="card"><div class="card-head"><div class="card-title">Resumo da operação</div></div><div class="card-body" id="saleV110Summary"></div></div></div></div>`;renderSaleStudentChipV110();renderSaleCartV110();renderPaymentsV110();await renderSalesKpisV110()}
async function renderSalesKpisV110(){const host=$('#salesKpisV110');if(!host)return;try{const snap=await db.collection('vendas').where('dataChave','==',dateKey()).get();const rows=snap.docs.map(d=>({id:d.id,...d.data()})),validRows=rows.filter(x=>!String(x.status||'').toLowerCase().includes('cancel'));const total=validRows.reduce((s,x)=>s+Number(x.valorBrutoCentavos||0),0);const by=m=>validRows.reduce((s,x)=>{const ps=x.pagamentos||[];if(ps.length)return s+ps.filter(p=>p.metodo===m).reduce((a,p)=>a+Number(p.valorAplicadoCentavos||0),0);return s+(x.formaPagamento===m?Number(x.valorBrutoCentavos||0):0)},0);host.innerHTML=`<div class="kpi clickable" tabindex="0" onclick="renderSalesHistoryV110('hoje')"><div class="kpi-label">Vendas hoje</div><div class="kpi-value">${fmt(total)}</div><div class="kpi-sub">${validRows.length} operações válidas${rows.length-validRows.length?` · ${rows.length-validRows.length} cancelada(s)`:''}</div><span class="kpi-arrow">›</span></div><div class="kpi green clickable" onclick="renderSalesHistoryV110('dinheiro')"><div class="kpi-label">Dinheiro hoje</div><div class="kpi-value">${fmt(by('dinheiro'))}</div><div class="kpi-sub">Movimenta caixa físico</div><span class="kpi-arrow">›</span></div><div class="kpi orange clickable" onclick="renderSalesHistoryV110('cartao')"><div class="kpi-label">Cartão hoje</div><div class="kpi-value">${fmt(by('cartao'))}</div><div class="kpi-sub">Bruto registrado</div><span class="kpi-arrow">›</span></div><div class="kpi clickable" onclick="renderSalesHistoryV110('pix')"><div class="kpi-label">Pix hoje</div><div class="kpi-value">${fmt(by('pix'))}</div><div class="kpi-sub">Por origem</div><span class="kpi-arrow">›</span></div>`}catch(e){console.warn('sales-kpis-v221',e);host.innerHTML=`<div class="alert danger">Não foi possível carregar os indicadores de vendas. <button class="btn btn-light" onclick="renderSalesKpisV110()">Tentar novamente</button></div>`}}
function renderSaleStudentChipV110(){const el=$('#saleV110StudentChip');if(!el)return;const a=saleStudentV110();el.innerHTML=a?`<div class="sale-student-chip"><div><strong>${esc(a.nome)}</strong><span class="muted">${esc(a.turma)} · Matrícula ${esc(a.matricula)}</span></div><button class="btn btn-outline" onclick="clearSaleStudentV110()">Trocar</button></div>`:`<div class="empty-soft">Nenhum aluno selecionado. A venda pode continuar sem aluno, mas débitos e farda exigem identificação.</div>`}
function addStructuredItemV110(item){ensureSaleStateV110().cart.push({id:uidLocal('item'),...item});renderSaleCartV110()}
function removeStructuredItemV110(id){const st=ensureSaleStateV110();st.cart=st.cart.filter(x=>x.id!==id);renderSaleCartV110()}
function changeStructuredQtyV110(id,delta){const x=ensureSaleStateV110().cart.find(i=>i.id===id);if(!x||['debito_conta','avulso'].includes(x.tipo))return;x.quantidade=Math.max(1,Number(x.quantidade||1)+delta);if(x.tipo==='farda')x.valorCentavos=x.quantidade*x.precoUnitarioCentavos;renderSaleCartV110()}
async function addDebtItemV110(){const st=ensureSaleStateV110();if(!st.studentId)return appMessage('Selecione um aluno para adicionar a dívida.');if(st.cart.some(x=>x.tipo==='debito_conta'))return appMessage('A dívida já está no carrinho.');const acc=await getAccount(st.studentId),v=Number(acc.dividaCentavos||0);if(v<=0)return appMessage('Este aluno não possui valor em aberto.');addStructuredItemV110({tipo:'debito_conta',alunoId:st.studentId,nome:'Débito da cantina em aberto',categoria:'Cantina',quantidade:1,precoUnitarioCentavos:v,valorCentavos:v})}
function openFreeItemV110(){openModal('Adicionar item avulso',`<div class="fg"><label>Descrição</label><input id="v110FreeDesc" class="fi" placeholder="Ex.: Passeio escolar"></div><div class="fg"><label>Categoria</label><select id="v110FreeCat" class="fi"><option>Passeio</option><option>Evento</option><option>Figurino</option><option>Paradidático</option><option>Taxa escolar</option><option>Outro</option></select></div><div class="fg"><label>Valor</label><input id="v110FreeValue" class="fi" placeholder="0,00" inputmode="decimal"></div><button class="btn btn-primary" style="width:100%" onclick="confirmFreeItemV110()">Adicionar ao carrinho</button>`)}
function confirmFreeItemV110(){const d=$('#v110FreeDesc').value.trim(),cat=$('#v110FreeCat').value,v=parseBRL($('#v110FreeValue').value);if(!d||v<=0)return appMessage('Informe descrição e valor.');addStructuredItemV110({tipo:'avulso',nome:d,categoria:cat,quantidade:1,precoUnitarioCentavos:v,valorCentavos:v});closeModal()}
function toggleV110UniformModel(){const big=['P','M','G','GG','XGG'].includes($('#v110UniformSize').value);$('#v110UniformModel').disabled=!big;if(!big)$('#v110UniformModel').value=''}

function removePaymentV110(id){const st=ensureSaleStateV110();st.payments=st.payments.filter(x=>x.id!==id);renderPaymentsV110()}
function resetStructuredSaleV110(){ensureSaleStateV110(true);renderSalesWorkspaceV110()}
function renderPaymentFieldsV110(){const host=$('#v110PayFields');if(!host)return;const m=$('#v110PayMethod').value,a=parseBRL($('#v110PayAmount').value),label=$('#v110PayAmountLabel');if(label)label.textContent=m==='cartao'?'Valor líquido recebido pela escola':'Valor aplicado nesta venda';if(m==='dinheiro')host.innerHTML=`<div class="fg"><label>Valor entregue pelo responsável</label><input id="v110CashTendered" class="fi" value="${(a/100).toFixed(2).replace('.',',')}" inputmode="decimal"></div><div class="alert">O caixa aumenta apenas pelo valor da venda. O excedente é troco.</div>`;if(m==='cartao')host.innerHTML=`<div class="form-row"><div class="fg"><label>Adquirente</label><select id="v110Acquirer" class="fi"><option value="rede_laranjinha">Rede / Laranjinha</option><option value="infinitepay">InfinitePay</option><option value="outra">Outra</option></select></div><div class="fg"><label>Modalidade</label><select id="v110CardMode" class="fi" onchange="$('#v110Installments').disabled=this.value!=='credito'"><option value="debito">Débito</option><option value="credito">Crédito</option></select></div></div><div class="form-row"><div class="fg"><label>Parcelas</label><input id="v110Installments" class="fi" type="number" min="1" value="1" disabled></div><div class="fg"><label>Valor bruto cobrado no cartão</label><input id="v110CardGross" class="fi" value="${(a/100).toFixed(2).replace('.',',')}" inputmode="decimal" oninput="this.dataset.manual='1'"></div></div><div class="alert">O líquido recebido quita a venda. A diferença para o bruto será registrada como taxa.</div><div class="fg"><label>Referência / NSU (opcional)</label><input id="v110CardNsu" class="fi" placeholder="Identificação da transação"></div>`;if(m==='pix')host.innerHTML=`<div class="fg"><label>Origem do Pix</label><select id="v110PixOrigin" class="fi"><option value="banco">Pix bancário</option><option value="rede_laranjinha">Rede / Laranjinha</option><option value="infinitepay">InfinitePay</option><option value="outro">Outro</option></select></div><div class="fg"><label>Referência (opcional)</label><input id="v110PixRef" class="fi" placeholder="Descrição ou identificador"></div>`}
function confirmPaymentV110(){const st=ensureSaleStateV110(),m=$('#v110PayMethod').value,a=parseBRL($('#v110PayAmount').value),rem=remainingSaleV110();if(a<=0||a>rem)return appMessage(`Informe um valor entre R$ 0,01 e ${fmt(rem)}.`);let p={id:uidLocal('pag'),metodo:m,valorAplicadoCentavos:a};if(m==='dinheiro'){const tender=parseBRL($('#v110CashTendered').value);if(tender<a)return appMessage('O valor entregue não pode ser menor que o valor aplicado.');p.valorRecebidoCentavos=tender;p.trocoCentavos=tender-a}if(m==='cartao'){const gross=parseBRL($('#v110CardGross').value);if(gross<a)return appMessage('O valor bruto cobrado não pode ser menor que o líquido recebido.');p.adquirente=$('#v110Acquirer').value;p.modalidadeCartao=$('#v110CardMode').value;p.parcelas=p.modalidadeCartao==='credito'?Math.max(1,Number($('#v110Installments').value||1)):1;p.valorBrutoPassadoCentavos=gross;p.valorLiquidoCentavos=a;p.taxaCentavos=gross-a;p.nsu=$('#v110CardNsu').value.trim()}if(m==='pix'){p.origemPix=$('#v110PixOrigin').value;p.referencia=$('#v110PixRef').value.trim()}st.payments.push(p);closeModal();renderPaymentsV110()}
function expandStructuredItemsV110(cart){const map={};for(const line of cart.filter(x=>x.tipo==='produto')){const p=productById(line.produtoId);for(const c of productComponents(p,line.quantidade||1)){if(!map[c.produtoId])map[c.produtoId]={...c};else map[c.produtoId].quantidade+=c.quantidade}}return Object.values(map)}

async function renderSalesHistoryV110(filter='hoje'){if(filter==='todos'&&typeof window.renderVendasV162==='function')return window.renderVendasV162('todos',{refresh:true});const el=$('#mainContent');el.innerHTML=pageHeader('Histórico de vendas','Investigue cada operação, composição e forma de pagamento.',`<button class="btn btn-outline" onclick="navigate('vendas')">← Nova venda</button>`)+`<div class="empty">Carregando...</div>`;try{const snap=await db.collection('vendas').where('dataChave','==',dateKey()).get();let rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm)));if(['dinheiro','cartao','pix'].includes(filter))rows=rows.filter(x=>(x.pagamentos||[]).some(p=>p.metodo===filter)||x.formaPagamento===filter);el.innerHTML=pageHeader('Histórico de vendas','Clique numa operação para ver a composição completa.',`<button class="btn btn-primary" onclick="navigate('vendas')">+ Nova venda</button>`)+`<div class="detail-toolbar"><div class="fg"><label>Filtro rápido</label><select class="fi" onchange="renderSalesHistoryV110(this.value)"><option value="hoje" ${filter==='hoje'?'selected':''}>Hoje</option><option value="todos">Todos</option><option value="dinheiro" ${filter==='dinheiro'?'selected':''}>Dinheiro</option><option value="cartao" ${filter==='cartao'?'selected':''}>Cartão</option><option value="pix" ${filter==='pix'?'selected':''}>Pix</option></select></div></div><div class="card">${rows.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Data</th><th>Operador</th><th>Aluno</th><th>Composição</th><th>Pagamento</th><th style="text-align:right">Bruto</th></tr></thead><tbody>${rows.map(r=>`<tr class="click-row" onclick="openSaleDetailsV110('${r.id}')"><td>${humanDate(r.criadoEm)}</td><td>${esc(r.operadorNome||'-')}</td><td>${esc(r.alunoNome||studentNameV110(r.alunoId)||'Sem aluno')}</td><td>${(r.itens||[]).slice(0,3).map(x=>esc(x.nome)).join(' + ')}${(r.itens||[]).length>3?'…':''}</td><td>${esc((r.pagamentos||[]).length?(r.pagamentos||[]).map(paymentLabelV110).join(' / '):(r.formaPagamento||'-'))}</td><td class="money">${fmt(r.valorBrutoCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma venda neste filtro.</div>'}</div>`}catch(e){console.warn('sales-history-v221',e);el.innerHTML=pageHeader('Histórico de vendas','Não foi possível consultar as vendas.',`<button class="btn btn-outline" onclick="navigate('vendas')">← Nova venda</button>`)+`<div class="alert danger">${esc(e.message||'Falha de leitura')}. <button class="btn btn-light" onclick="renderSalesHistoryV110('${esc(filter)}')">Tentar novamente</button></div>`}}
async function openSaleDetailsV110(id){const snap=await db.collection('vendas').doc(id).get();if(!snap.exists)return;const r={id:snap.id,...snap.data()};openModal('Detalhes da venda',`<div class="sale-number">Venda ${esc(r.id.slice(-10).toUpperCase())}</div><p class="muted">${humanDate(r.criadoEm)} · ${esc(r.operadorNome||'-')} · ${esc(r.alunoNome||'Sem aluno')}</p><div class="card-title" style="margin:15px 0 7px">Composição</div>${(r.itens||[]).map(x=>`<div class="sale-item"><div><strong>${esc(x.nome)}</strong><div class="sale-item-meta">${esc(itemKindLabelV110(x))}${x.categoria?` · ${esc(x.categoria)}`:''}</div></div><strong>${fmt(centsOfLine(x))}</strong></div>`).join('')}<div class="sale-total"><span>Total bruto</span><span>${fmt(r.valorBrutoCentavos)}</span></div><div class="card-title" style="margin:15px 0 7px">Pagamentos</div>${(r.pagamentos||[]).length?(r.pagamentos||[]).map(p=>`<div class="payment-card"><strong>${esc(paymentLabelV110(p))}</strong><div class="payment-breakdown">Aplicado ${fmt(p.valorAplicadoCentavos)}${p.metodo==='cartao'?` · Líquido ${fmt(p.valorLiquidoCentavos||p.valorAplicadoCentavos)} · Bruto cobrado ${fmt(p.valorBrutoPassadoCentavos)} · Taxa ${fmt(p.taxaCentavos)}`:''}${p.metodo==='dinheiro'?` · Troco ${fmt(p.trocoCentavos)}`:''}</div></div>`).join(''):`<div class="alert">Forma registrada: ${esc(r.formaPagamento||'-')}</div>`}<div class="actions" style="margin-top:15px"><button class="btn btn-primary" onclick="downloadSaleReceiptPdfV110('${r.id}')">Comprovante PDF</button></div>`)}

async function renderInsightV110(type){
  const el=$('#mainContent');
  el.innerHTML=pageHeader('Detalhamento','Carregando...',`<button class="btn btn-outline" onclick="navigate('dashboard')">← Resumo</button>`)+`<div class="empty">Carregando...</div>`;
  try{
    if(type==='sales'){
      const s=await db.collection('vendas').where('dataChave','==',dateKey()).get();
      const rows=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!String(x.status||'').toLowerCase().includes('cancel')).sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm)));
      el.innerHTML=pageHeader('Vendas de hoje','Operações válidas que formam o KPI.',`<button class="btn btn-outline" onclick="navigate('dashboard')">← Resumo</button>`)+saleRowsTableV110(rows);return;
    }
    if(type==='debts'||type==='blocked'){
      if(typeof ensureStudentsLoadedV218==='function')await ensureStudentsLoadedV218();
      const accounts=typeof window.loadAllFinancialAccountsV221==='function'?await window.loadAllFinancialAccountsV221():[];
      let rows=type==='debts'?accounts.filter(x=>Number(x.dividaCentavos||0)>0):accounts.filter(x=>x.bloqueadoPorLimite||x.bloqueioManual);
      rows.sort((a,b)=>Number(b.dividaCentavos||0)-Number(a.dividaCentavos||0));
      const title=type==='debts'?'Contas familiares com valores em aberto':'Contas familiares bloqueadas';
      el.innerHTML=pageHeader(title,'Lista completa das contas que formam o indicador.',`<button class="btn btn-outline" onclick="navigate('dashboard')">← Resumo</button>`)+`<div class="card">${rows.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Aluno / família</th><th>Turma</th><th style="text-align:right">Em aberto</th><th style="text-align:right">Limite</th><th>Situação</th></tr></thead><tbody>${rows.map(r=>{const studentId=r.alunoPrincipalId||(r.alunosIds||[])[0]||null,a=(state.students||[]).find(x=>String(x.id)===String(studentId));return `<tr class="${studentId?'click-row':''}" ${studentId?`onclick="openStudentDetails('${esc(studentId)}')"`:''}><td><strong>${esc(a?.nome||r.responsavelNome||'Conta familiar')}</strong><br><span class="muted">${esc(r.responsavelNome||r.responsavelId||r.id||'')}</span></td><td>${esc(a?.turma||'-')}</td><td class="money">${fmt(r.dividaCentavos)}</td><td class="money">${fmt(r.limiteFiadoCentavos)}</td><td><span class="badge ${r.bloqueadoPorLimite||r.bloqueioManual?'b-red':'b-green'}">${r.bloqueioManual?'manual':r.bloqueadoPorLimite?'limite':'liberada'}</span></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Nenhum registro.</div>'}</div>`;return;
    }
    if(type==='uniforms'){
      const all=typeof window.allCollectionRowsV221==='function'?await window.allCollectionRowsV221('pedidos_farda',100):(await db.collection('pedidos_farda').get()).docs.map(d=>({id:d.id,...d.data()}));
      const rows=all.filter(x=>!['entregue','cancelado'].includes(x.statusAtendimento)).sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm)));
      el.innerHTML=pageHeader('Fardas pendentes','Pedidos ainda não concluídos.',`<button class="btn btn-outline" onclick="navigate('dashboard')">← Resumo</button>`)+`<div class="card">${rows.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Aluno</th><th>Variação</th><th>Status</th><th style="text-align:right">Total</th></tr></thead><tbody>${rows.map(r=>`<tr class="click-row" onclick="updateUniformStatus('${r.id}')"><td>${esc(r.alunoNome)}</td><td>${esc(r.tamanho)} ${esc(r.modelo||'')}</td><td><span class="badge b-blue">${esc(String(r.statusAtendimento||'').replaceAll('_',' '))}</span></td><td class="money">${fmt(r.totalCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma farda pendente.</div>'}</div>`;return;
    }
    if(type==='deliveries'){await renderEntregas();return}
  }catch(e){console.warn('insight-v221',type,e);el.innerHTML=pageHeader('Detalhamento','Não foi possível carregar estes dados.',`<button class="btn btn-outline" onclick="navigate('dashboard')">← Resumo</button>`)+`<div class="alert danger">${esc(e.message||'Falha de leitura')}. <button class="btn btn-light" onclick="renderInsightV110('${esc(type)}')">Tentar novamente</button></div>`}
}
function saleRowsTableV110(rows){return `<div class="card">${rows.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Hora</th><th>Operador</th><th>Aluno</th><th>Composição</th><th>Forma</th><th style="text-align:right">Valor</th></tr></thead><tbody>${rows.map(r=>`<tr class="click-row" onclick="openSaleDetailsV110('${r.id}')"><td>${humanDate(r.criadoEm)}</td><td>${esc(r.operadorNome||'-')}</td><td>${esc(r.alunoNome||'Sem aluno')}</td><td>${(r.itens||[]).map(x=>esc(x.nome)).join(' + ')||'-'}</td><td>${esc((r.pagamentos||[]).length?(r.pagamentos||[]).map(paymentLabelV110).join(' / '):(r.formaPagamento||'-'))}</td><td class="money">${fmt(r.valorBrutoCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma venda.</div>'}</div>`}

function parentUrl(a){const base=location.origin+location.pathname;return `${base}?modo=pai&matricula=${encodeURIComponent(a.matricula)}`}
async function qrDataUrlV110(text,size=180){return new Promise(resolve=>{const wrap=document.createElement('div');wrap.style.position='fixed';wrap.style.left='-10000px';wrap.style.top='0';document.body.appendChild(wrap);new QRCode(wrap,{text,width:size,height:size,correctLevel:QRCode.CorrectLevel.M});setTimeout(()=>{const c=wrap.querySelector('canvas'),img=wrap.querySelector('img');const url=c?c.toDataURL('image/png'):img?.src||'';wrap.remove();resolve(url)},120)})}
function openDebtRowsForReportV110(allMoves){return computeOpenDebtLines(allMoves).map(m=>({data:humanDate(m.criadoEm),itens:(m.itens||[]).map(x=>`${x.quantidade}× ${x.nome}`).join(', ')||'Consumo',valorCentavos:Number(m.abertoCentavos||0)}))}
async function generateReport(id){const a=state.students.find(x=>x.id===id),acc=await getAccount(id),snap=await db.collection('movimentos_conta').where('alunoId','==',id).limit(250).get(),rows=openDebtRowsForReportV110(snap.docs.map(d=>d.data())),link=parentUrl(a);state.currentReportV110={type:'student',student:a,account:acc,rows,link};const qr=await qrDataUrlV110(link,150);$('#reportHost').classList.remove('hidden');$('#reportHost').innerHTML=`<div id="reportSheet" class="wa-report"><div class="wa-head"><div><div class="wa-brand">Escola Piaget</div><div class="wa-title">Demonstrativo de valores em aberto</div><div class="muted">Relatório de valores em aberto</div></div><img src="${qr}" width="122" height="122" alt="QR Code"></div><div class="wa-student"><strong>${esc(a.nome)}</strong><div>${esc(a.turma)} · Matrícula ${esc(a.matricula)}</div><div class="muted">Emitido em ${new Date().toLocaleString('pt-BR')}</div></div><table class="wa-table"><thead><tr><th>Data</th><th>Itens</th><th style="text-align:right">Em aberto</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.data)}</td><td>${esc(r.itens)}</td><td style="text-align:right;font-weight:800">${fmt(r.valorCentavos)}</td></tr>`).join('')||'<tr><td colspan="3">Sem consumos em aberto detalhados.</td></tr>'}</tbody></table><div class="wa-total"><span>Total em aberto</span><strong>${fmt(acc.dividaCentavos)}</strong></div><div class="wa-footer"><img src="${qr}" width="100" height="100" alt="QR Code"><p><strong>Acesse a conta do aluno para pagar.</strong><br>${esc(link)}<br><br>Limite autorizado: ${fmt(acc.limiteFiadoCentavos)} · Compra sem saldo: ${acc.autorizadoSemSaldo?'Liberada':'Bloqueada'}</p></div></div>`;openModal('Demonstrativo de valores em aberto',`<div class="alert">Documento reconstruído em template próprio. O PDF é vetorial e multipágina; a imagem usa um layout separado para WhatsApp.</div><div class="actions" style="margin-top:14px"><button class="btn btn-primary" onclick="downloadReportPdf('${esc(a.matricula)}')">Baixar PDF A4</button><button class="btn btn-orange" onclick="downloadReportPng('${esc(a.matricula)}')">Baixar imagem</button><button class="btn btn-light" onclick="copyParentLink('${id}')">Copiar link</button></div>`)}
async function downloadReportPdf(mat){const r=state.currentReportV110;if(!r||r.type!=='student')return;const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),blue=[44,56,150],orange=[255,152,31],link=r.link,qr=await qrDataUrlV110(link,220);let y=18;pdf.setFillColor(...blue);pdf.rect(0,0,210,8,'F');pdf.setTextColor(...blue);pdf.setFont('helvetica','bold');pdf.setFontSize(19);pdf.text('Escola Piaget — Demonstrativo de valores em aberto',15,y);pdf.addImage(qr,'PNG',165,13,28,28);pdf.setTextColor(20,24,40);pdf.setFontSize(12);y+=9;pdf.setFont('helvetica','bold');pdf.text(r.student.nome,15,y);pdf.setFont('helvetica','normal');pdf.setFontSize(10);y+=5;pdf.text(`${r.student.turma} · Matrícula ${r.student.matricula}`,15,y);y+=5;pdf.setTextColor(100);pdf.text(`Emitido em ${new Date().toLocaleString('pt-BR')}`,15,y);y=48;const drawHead=()=>{pdf.setFillColor(238,240,248);pdf.rect(15,y,180,8,'F');pdf.setTextColor(70);pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.text('DATA',17,y+5.2);pdf.text('ITENS',49,y+5.2);pdf.text('EM ABERTO',172,y+5.2);y+=9};drawHead();pdf.setFont('helvetica','normal');pdf.setTextColor(25);for(const row of r.rows){const lines=pdf.splitTextToSize(row.itens,112),h=Math.max(8,lines.length*4.4+3);if(y+h>265){pdf.addPage();y=17;drawHead()}pdf.setDrawColor(225);pdf.line(15,y+h,195,y+h);pdf.setFontSize(9);pdf.text(row.data,17,y+5);pdf.text(lines,49,y+5);pdf.setFont('helvetica','bold');pdf.text(fmt(row.valorCentavos).replace(/\u00a0/g,' '),193,y+5,{align:'right'});pdf.setFont('helvetica','normal');y+=h}if(y>245){pdf.addPage();y=20}pdf.setFillColor(...blue);pdf.roundedRect(15,y+4,180,18,3,3,'F');pdf.setTextColor(255);pdf.setFont('helvetica','bold');pdf.setFontSize(11);pdf.text('TOTAL EM ABERTO',20,y+15);pdf.setFontSize(17);pdf.text(fmt(r.account.dividaCentavos).replace(/\u00a0/g,' '),190,y+16,{align:'right'});y+=30;pdf.setTextColor(25);pdf.setFontSize(9);pdf.setFont('helvetica','normal');pdf.text(`Limite autorizado: ${fmt(r.account.limiteFiadoCentavos).replace(/\u00a0/g,' ')} · Compra sem saldo: ${r.account.autorizadoSemSaldo?'Liberada':'Bloqueada'}`,15,y);y+=7;pdf.setTextColor(...blue);pdf.textWithLink('Abrir conta do aluno e pagar',15,y,{url:link});pdf.setTextColor(100);pdf.setFontSize(7);y+=5;pdf.text(pdf.splitTextToSize(link,145),15,y);pdf.save(`demonstrativo-valores-em-aberto-${mat}.pdf`)}
async function downloadReportPng(mat){const node=$('#reportSheet');if(!node)return;await document.fonts?.ready;const canvas=await html2canvas(node,{scale:2,backgroundColor:'#ffffff',useCORS:true,logging:false});const a=document.createElement('a');a.download=`demonstrativo-valores-em-aberto-${mat}.png`;a.href=canvas.toDataURL('image/png');a.click()}
async function downloadSaleReceiptPdfV110(id){const s=await db.collection('vendas').doc(id).get();if(!s.exists)return;const r=s.data(),{jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'});let y=18;pdf.setFillColor(44,56,150);pdf.rect(0,0,210,8,'F');pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.setFontSize(18);pdf.text('Escola Piaget — Comprovante de venda',15,y);pdf.setTextColor(30);pdf.setFontSize(10);pdf.setFont('helvetica','normal');y+=8;pdf.text(`Venda: ${r.id}`,15,y);y+=5;pdf.text(`Data: ${humanDate(r.criadoEm)} · Operador: ${r.operadorNome||'-'}`,15,y);y+=5;pdf.text(`Aluno: ${r.alunoNome||'Sem aluno'}`,15,y);y+=10;pdf.setFillColor(238,240,248);pdf.rect(15,y,180,8,'F');pdf.setFont('helvetica','bold');pdf.text('COMPOSIÇÃO',17,y+5.2);y+=11;for(const x of r.itens||[]){const desc=`${x.nome}${x.categoria?` · ${x.categoria}`:''}`,lines=pdf.splitTextToSize(desc,135),h=Math.max(7,lines.length*4+2);if(y+h>270){pdf.addPage();y=18}pdf.setFont('helvetica','normal');pdf.text(lines,17,y+4);pdf.setFont('helvetica','bold');pdf.text(fmt(centsOfLine(x)).replace(/\u00a0/g,' '),193,y+4,{align:'right'});pdf.setDrawColor(230);pdf.line(15,y+h,195,y+h);y+=h}y+=5;pdf.setFontSize(15);pdf.text(`TOTAL: ${fmt(r.valorBrutoCentavos).replace(/\u00a0/g,' ')}`,193,y,{align:'right'});y+=12;pdf.setFontSize(10);pdf.text('PAGAMENTOS',15,y);y+=6;pdf.setFont('helvetica','normal');for(const p of r.pagamentos||[]){pdf.text(`${paymentLabelV110(p)} — ${fmt(p.valorAplicadoCentavos).replace(/\u00a0/g,' ')}`,17,y);y+=5}pdf.save(`venda-${r.id.slice(-10)}.pdf`)}

async function renderCaixa(){const point=state.user.perfil==='cantina'?'cantina':'secretaria',shift=state.user.perfil==='cantina'?(state.recessGroup==='tarde'?'tarde':'manha'):(state.user.turnos?.[0]||'manha'),id=`${point}_${dateKey()}_${shift}`,ref=db.collection('caixas').doc(id),snap=await ref.get(),cash=snap.exists?{id,...snap.data()}:null;let moves=[];if(cash){const ms=await db.collection('movimentos_caixa').where('caixaId','==',id).limit(500).get();moves=ms.docs.map(d=>d.data())}const initial=Number(cash?.valorInicialCentavos||0),sales=moves.filter(x=>x.tipo==='venda').reduce((s,x)=>s+Number(x.valorCentavos||0),0),transfersOut=moves.filter(x=>['transferencia_saida','suprimento_cantina'].includes(x.tipo)).reduce((s,x)=>s+Number(x.valorCentavos||0),0),expected=initial+sales-transfersOut;state.currentCashReportV110={cash,moves,point,shift,initial,sales,expected};$('#mainContent').innerHTML=pageHeader(`Caixa da ${point}`,'Conferência física e memória de cálculo.',cash?`<button class="btn btn-outline" onclick="downloadCashPdfV110()">Relatório PDF</button>`:'')+`<div class="grid g3"><div class="kpi clickable" onclick="showCashMemoryV110()"><div class="kpi-label">Situação</div><div class="kpi-value">${cash?.status==='aberto'?'Aberto':'Fechado / não aberto'}</div><div class="kpi-sub">${shift}</div><span class="kpi-arrow">›</span></div><div class="kpi green clickable" onclick="showCashMovesV110()"><div class="kpi-label">Vendas em dinheiro</div><div class="kpi-value">${fmt(sales)}</div><div class="kpi-sub">Clique para ver movimentos</div><span class="kpi-arrow">›</span></div><div class="kpi orange clickable" onclick="showCashMemoryV110()"><div class="kpi-label">Saldo esperado</div><div class="kpi-value">${fmt(expected)}</div><div class="kpi-sub">Memória de cálculo</div><span class="kpi-arrow">›</span></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="card-head"><div class="card-title">Operação</div></div><div class="card-body">${!cash||cash.status!=='aberto'?`<button class="btn btn-primary" onclick="openCash('${point}','${shift}')">Abrir caixa</button>`:`<div class="fg"><label>Valor contado / devolvido</label><input class="fi" id="cashCounted" placeholder="0,00"></div><button class="btn btn-orange" onclick="closeCash('${id}',${expected})">Fechar e devolver</button>`}</div></div><div class="card"><div class="card-head"><div class="card-title">Movimentos</div></div><div>${moves.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Data</th><th>Tipo</th><th style="text-align:right">Valor</th></tr></thead><tbody>${moves.sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm))).map(m=>`<tr><td>${humanDate(m.criadoEm)}</td><td>${esc(String(m.tipo||'').replaceAll('_',' '))}</td><td class="money">${fmt(m.valorCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem movimentos.</div>'}</div></div></div>`}
function showCashMemoryV110(){const r=state.currentCashReportV110;if(!r)return;openModal('Memória do caixa',`<div class="mini-breakdown"><span><span>Saldo inicial</span><strong>${fmt(r.initial)}</strong></span><span><span>Vendas em dinheiro</span><strong>${fmt(r.sales)}</strong></span><span><span>Saldo esperado</span><strong>${fmt(r.expected)}</strong></span>${r.cash?.valorContadoCentavos!=null?`<span><span>Saldo contado</span><strong>${fmt(r.cash.valorContadoCentavos)}</strong></span><span><span>Diferença</span><strong>${fmt(r.cash.diferencaCentavos)}</strong></span>`:''}</div>`)}
function showCashMovesV110(){const r=state.currentCashReportV110;if(!r)return;openModal('Movimentos do caixa',r.moves.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th style="text-align:right">Valor</th></tr></thead><tbody>${r.moves.map(m=>`<tr><td>${humanDate(m.criadoEm)}</td><td>${esc(m.tipo)}</td><td class="money">${fmt(m.valorCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem movimentos.</div>')}
async function downloadCashPdfV110(){const r=state.currentCashReportV110;if(!r?.cash)return;const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'});pdf.setFillColor(44,56,150);pdf.rect(0,0,210,8,'F');pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.setFontSize(18);pdf.text(`Escola Piaget — Fechamento de caixa`,15,19);pdf.setTextColor(30);pdf.setFontSize(10);pdf.setFont('helvetica','normal');pdf.text(`Ponto: ${r.point} · Turno: ${r.shift} · Data: ${dateKey()}`,15,28);let y=40;const lines=[['Saldo inicial',r.initial],['Vendas em dinheiro',r.sales],['Saldo esperado',r.expected],['Saldo contado',r.cash.valorContadoCentavos],['Diferença',r.cash.diferencaCentavos]];for(const [label,val] of lines){if(val==null)continue;pdf.setDrawColor(225);pdf.line(15,y+6,195,y+6);pdf.text(label,17,y+4);pdf.setFont('helvetica','bold');pdf.text(fmt(val).replace(/\u00a0/g,' '),193,y+4,{align:'right'});pdf.setFont('helvetica','normal');y+=9}y+=7;pdf.setFont('helvetica','bold');pdf.text('MOVIMENTOS',15,y);y+=7;pdf.setFont('helvetica','normal');for(const m of r.moves.sort((a,b)=>String(a.criadoEm).localeCompare(String(b.criadoEm)))){if(y>275){pdf.addPage();y=18}pdf.text(humanDate(m.criadoEm),15,y);pdf.text(String(m.tipo||'').replaceAll('_',' '),55,y);pdf.text(fmt(m.valorCentavos).replace(/\u00a0/g,' '),193,y,{align:'right'});y+=6}pdf.save(`fechamento-caixa-${r.point}-${dateKey()}.pdf`)}

