
/* =========================================================
   Escola Piaget — V1.2.1
   Marca nos documentos + caixas consolidados + fechamento auditável
   ========================================================= */
const V121_VERSION='1.2.1-dev';
const _brandCacheV121={};

async function brandDataUrlV121(path){
  if(_brandCacheV121[path])return _brandCacheV121[path];
  _brandCacheV121[path]=(async()=>{const res=await fetch(path);if(!res.ok)throw new Error('Não foi possível carregar a identidade visual.');const blob=await res.blob();return await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(blob)})})();
  return _brandCacheV121[path];
}
async function drawPdfBrandHeaderV121(pdf,title,subtitle=''){
  const icon=await brandDataUrlV121(BRAND_V120.icon);
  pdf.setFillColor(255,255,255);pdf.rect(0,0,210,50,'F');
  pdf.addImage(icon,'PNG',14,8,19,19);
  pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.setFontSize(18);pdf.text(title,41,18);
  if(subtitle){pdf.setTextColor(92,99,120);pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.text(pdf.splitTextToSize(subtitle,154),41,25)}
  pdf.setDrawColor(255,152,31);pdf.setLineWidth(1.4);pdf.line(14,46,196,46);pdf.setLineWidth(.2);
  return 54;
}
async function drawPdfContinuationHeaderV121(pdf,title){
  const icon=await brandDataUrlV121(BRAND_V120.icon);pdf.addImage(icon,'PNG',15,7,12,12);pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.setFontSize(12);pdf.text(title,34,14);pdf.setDrawColor(255,152,31);pdf.line(15,21,195,21);return 27;
}
function applyBrandingV121(){
  const logo=document.querySelector('.brand-logo');if(logo)logo.innerHTML=`<img src="${BRAND_V120.icon}" alt="Símbolo Escola Piaget">`;
  const brandTitle=document.querySelector('.brand h1');if(brandTitle)brandTitle.textContent='Escola Piaget';
  const parentHero=document.querySelector('#parentScreen .parent-hero');if(parentHero){const old=parentHero.querySelector('img');if(old){old.src=BRAND_V120.icon;old.className='v121-parent-icon';old.removeAttribute('style')}}
}
/* inicialização herdada consolidada pela V1.5.0-dev2 */

/* ---------- Documento de conta / WhatsApp ---------- */
window.generateReport=async function(id){
  const a=state.students.find(x=>x.id===id),acc=await getAccount(id),snap=await db.collection('movimentos_conta').where('alunoId','==',id).limit(300).get(),rows=openDebtRowsForReportV110(snap.docs.map(d=>d.data())),link=parentUrl(a);
  state.currentReportV110={type:'student',student:a,account:acc,rows,link};const qr=await qrDataUrlV110(link,150);
  $('#reportHost').classList.remove('hidden');
  $('#reportHost').innerHTML=`<div id="reportSheet" class="wa-report"><div class="wa-head"><div class="wa-brand-lockup-v121"><img src="${BRAND_V120.full}" alt="Escola Piaget"><div class="wa-brand-copy-v121"><div class="wa-title">Demonstrativo de valores em aberto</div><div class="muted">Relatório de valores em aberto</div></div></div><img src="${qr}" width="122" height="122" alt="QR Code"></div><div class="wa-student"><strong>${esc(a.nome)}</strong><div>${esc(a.turma)} · Matrícula ${esc(a.matricula)}</div><div class="muted">Emitido em ${new Date().toLocaleString('pt-BR')}</div></div><table class="wa-table"><thead><tr><th>Data</th><th>Itens</th><th style="text-align:right">Em aberto</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.data)}</td><td>${esc(r.itens)}</td><td style="text-align:right;font-weight:800">${fmt(r.valorCentavos)}</td></tr>`).join('')||'<tr><td colspan="3">Sem consumos em aberto detalhados.</td></tr>'}</tbody></table><div class="wa-total"><span>Total em aberto</span><strong>${fmt(acc.dividaCentavos)}</strong></div><div class="wa-footer"><img src="${qr}" width="100" height="100" alt="QR Code"><p><strong>Acesse a conta do aluno para pagar.</strong><br>${esc(link)}<br><br>Limite autorizado: ${fmt(acc.limiteFiadoCentavos)} · Compra sem saldo: ${acc.autorizadoSemSaldo?'Liberada':'Bloqueada'}</p></div></div>`;
  openModal('Demonstrativo de valores em aberto',`<div class="alert">PDF A4 e imagem para WhatsApp agora usam a identidade visual oficial da Escola Piaget.</div><div class="actions" style="margin-top:14px"><button class="btn btn-primary" onclick="downloadReportPdf('${esc(a.matricula)}')">Baixar PDF A4</button><button class="btn btn-orange" onclick="downloadReportPng('${esc(a.matricula)}')">Baixar imagem</button><button class="btn btn-light" onclick="copyParentLink('${id}')">Copiar link</button></div>`)
}
window.downloadReportPdf=async function(mat){
  const r=state.currentReportV110;if(!r||r.type!=='student')return;const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),blue=[44,56,150],link=r.link,qr=await qrDataUrlV110(link,220);
  let y=await drawPdfBrandHeaderV121(pdf,'Demonstrativo de valores em aberto','Relatório de valores em aberto');pdf.addImage(qr,'PNG',165,55,28,28);
  pdf.setTextColor(20,24,40);pdf.setFont('helvetica','bold');pdf.setFontSize(12);pdf.text(r.student.nome,15,y+4);pdf.setFont('helvetica','normal');pdf.setFontSize(10);pdf.text(`${r.student.turma} · Matrícula ${r.student.matricula}`,15,y+10);pdf.setTextColor(100);pdf.text(`Emitido em ${new Date().toLocaleString('pt-BR')}`,15,y+16);y=88;
  const drawHead=()=>{pdf.setFillColor(238,240,248);pdf.rect(15,y,180,8,'F');pdf.setTextColor(70);pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.text('DATA',17,y+5.2);pdf.text('ITENS',49,y+5.2);pdf.text('EM ABERTO',172,y+5.2);y+=9};drawHead();pdf.setFont('helvetica','normal');pdf.setTextColor(25);
  for(const row of r.rows){const lines=pdf.splitTextToSize(row.itens,112),h=Math.max(8,lines.length*4.4+3);if(y+h>265){pdf.addPage();y=await drawPdfContinuationHeaderV121(pdf,'Demonstrativo de valores em aberto');drawHead()}pdf.setDrawColor(225);pdf.line(15,y+h,195,y+h);pdf.setFontSize(9);pdf.text(row.data,17,y+5);pdf.text(lines,49,y+5);pdf.setFont('helvetica','bold');pdf.text(fmt(row.valorCentavos).replace(/\u00a0/g,' '),193,y+5,{align:'right'});pdf.setFont('helvetica','normal');y+=h}
  if(y>242){pdf.addPage();y=await drawPdfContinuationHeaderV121(pdf,'Demonstrativo de valores em aberto')}
  pdf.setFillColor(...blue);pdf.roundedRect(15,y+4,180,18,3,3,'F');pdf.setTextColor(255);pdf.setFont('helvetica','bold');pdf.setFontSize(11);pdf.text('TOTAL EM ABERTO',20,y+15);pdf.setFontSize(17);pdf.text(fmt(r.account.dividaCentavos).replace(/\u00a0/g,' '),190,y+16,{align:'right'});y+=30;pdf.setTextColor(25);pdf.setFontSize(9);pdf.setFont('helvetica','normal');pdf.text(`Limite autorizado: ${fmt(r.account.limiteFiadoCentavos).replace(/\u00a0/g,' ')} · Compra sem saldo: ${r.account.autorizadoSemSaldo?'Liberada':'Bloqueada'}`,15,y);y+=7;pdf.setTextColor(...blue);pdf.textWithLink('Abrir conta do aluno e pagar',15,y,{url:link});pdf.setTextColor(100);pdf.setFontSize(7);y+=5;pdf.text(pdf.splitTextToSize(link,145),15,y);pdf.save(`demonstrativo-valores-em-aberto-${mat}.pdf`)
}

/* ---------- Comprovante de venda com marca ---------- */
window.downloadSaleReceiptPdfV110=async function(id){
  const s=await db.collection('vendas').doc(id).get();if(!s.exists)return;const r=s.data(),{jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'});let y=await drawPdfBrandHeaderV121(pdf,'Comprovante de venda',`Operação ${String(r.id||id).slice(-10)}`);
  pdf.setTextColor(30);pdf.setFontSize(10);pdf.setFont('helvetica','normal');if(String(r.status||'').toLowerCase().includes('cancel')){pdf.setFillColor(255,235,235);pdf.roundedRect(15,y,180,16,2,2,'F');pdf.setTextColor(170,35,35);pdf.setFont('helvetica','bold');pdf.text('VENDA CANCELADA — SEM VALIDADE FINANCEIRA',20,y+6);pdf.setFontSize(8);pdf.text(pdf.splitTextToSize(r.motivoCancelamento||'Cancelamento operacional',165),20,y+11);y+=22;pdf.setTextColor(30);pdf.setFontSize(10);pdf.setFont('helvetica','normal')}pdf.text(`Venda: ${r.id||id}`,15,y);y+=6;pdf.text(`Data: ${humanDate(r.criadoEm)} · Operador: ${r.operadorNome||'-'}`,15,y);y+=6;pdf.text(`Aluno: ${r.alunoNome||'Sem aluno'}`,15,y);y+=10;pdf.setFillColor(238,240,248);pdf.rect(15,y,180,8,'F');pdf.setFont('helvetica','bold');pdf.text('COMPOSIÇÃO',17,y+5.2);y+=11;
  for(const x of r.itens||[]){const desc=`${x.nome}${x.categoria?` · ${x.categoria}`:''}`,lines=pdf.splitTextToSize(desc,135),h=Math.max(7,lines.length*4+2);if(y+h>270){pdf.addPage();y=await drawPdfContinuationHeaderV121(pdf,'Comprovante de venda')}pdf.setFont('helvetica','normal');pdf.text(lines,17,y+4);pdf.setFont('helvetica','bold');pdf.text(fmt(centsOfLine(x)).replace(/\u00a0/g,' '),193,y+4,{align:'right'});pdf.setDrawColor(230);pdf.line(15,y+h,195,y+h);y+=h}
  y+=5;pdf.setTextColor(44,56,150);pdf.setFontSize(15);pdf.setFont('helvetica','bold');pdf.text(`TOTAL: ${fmt(r.valorBrutoCentavos).replace(/\u00a0/g,' ')}`,193,y,{align:'right'});y+=12;pdf.setTextColor(30);pdf.setFontSize(10);pdf.text('PAGAMENTOS',15,y);y+=6;pdf.setFont('helvetica','normal');for(const p of r.pagamentos||[]){pdf.text(`${paymentLabelV110(p)} — ${fmt(p.valorAplicadoCentavos).replace(/\u00a0/g,' ')}`,17,y);y+=5}pdf.save(`venda-${String(r.id||id).slice(-10)}.pdf`)
}

/* ---------- Caixa: cálculo, gestão consolidada e fechamento auditável ---------- */
function cashMovementEffectV121(m){const v=Number(m.valorCentavos||0),t=String(m.tipo||'');if(t==='venda'||t==='estorno_venda'||t==='transferencia_entrada'||t==='transferencia_entrada_cantina'||t==='ajuste_entrada')return v;if(['transferencia_saida','transferencia_saida_secretaria','suprimento_cantina','sangria','despesa','retirada','ajuste_saida','reembolso_venda'].includes(t))return-v;return 0}
function cashMetricsV121(cash,moves){const initial=Number(cash?.valorInicialCentavos||0),sales=(moves||[]).filter(x=>['venda','estorno_venda'].includes(x.tipo)).reduce((s,x)=>s+Number(x.valorCentavos||0),0),effects=(moves||[]).reduce((s,m)=>s+cashMovementEffectV121(m),0),expected=initial+effects;return{initial,sales,effects,expected,counted:cash?.valorContadoCentavos,diff:cash?.diferencaCentavos}}
async function cashRowsForDateV121(day){
  const cashDocs=await cashPagedDocsLegacyV221(db.collection('caixas').where('dataChave','==',day),100);
  const cashes=cashDocs.map(d=>({id:d.id,...d.data()}));const rows=await Promise.all(cashes.map(async cash=>{const moveDocs=await cashPagedDocsLegacyV221(db.collection('movimentos_caixa').where('caixaId','==',cash.id),250);const moves=moveDocs.map(d=>({id:d.id,...d.data()}));return{cash,moves,metrics:cashMetricsV121(cash,moves)}}));
  return rows.sort((a,b)=>`${a.cash.ponto}_${a.cash.turno}`.localeCompare(`${b.cash.ponto}_${b.cash.turno}`))
}
function cashPointLabelV121(p){return p==='cantina'?'Cantina':p==='secretaria'?'Secretaria':String(p||'-')}
function cashShiftLabelV121(s){return s==='manha'?'Manhã':s==='tarde'?'Tarde':String(s||'-')}
window.renderCaixa=async function(){if(state.user?.perfil==='gestao')return renderCashManagementV121();return renderOperationalCashV121()}
async function renderOperationalCashV121(){
  const point=state.user.perfil==='cantina'?'cantina':'secretaria',shift=state.user.perfil==='cantina'?(state.recessGroup==='tarde'?'tarde':'manha'):(state.user.turnos?.[0]||'manha'),id=`${point}_${dateKey()}_${shift}`,ref=db.collection('caixas').doc(id),snap=await ref.get(),cash=snap.exists?{id,...snap.data()}:null;let moves=[];if(cash){const moveDocs=await cashPagedDocsLegacyV221(db.collection('movimentos_caixa').where('caixaId','==',id),250);moves=moveDocs.map(d=>({id:d.id,...d.data()}))}const metrics=cashMetricsV121(cash,moves),displayExpected=cash?.valorEsperadoRegistradoCentavos??metrics.expected;state.currentCashReportV110={cash,moves,point,shift,...metrics,expected:displayExpected};
  const closure=cash?.status==='fechado'?`<div class="v121-signature"><strong>Assinatura operacional:</strong> ${esc(cash.fechadoPorNome||cash.assinaturaOperacional?.nome||'-')}<br><strong>Em:</strong> ${cash.fechadoEm?humanDate(cash.fechadoEm):'-'}${Number(cash.diferencaCentavos||0)!==0?`<div class="v121-justification"><strong>Justificativa da divergência:</strong><br>${esc(cash.justificativaDivergencia||'Não informada')}</div>`:''}</div>`:'';
  $('#mainContent').innerHTML=pageHeader(`Caixa da ${cashPointLabelV121(point)}`,'Conferência física, movimentos e fechamento identificado.',cash?`<button class="btn btn-outline" onclick="downloadCashPdfV110()">Relatório PDF</button>`:'')+`<div class="grid g3"><div class="kpi clickable" onclick="showCashMemoryV110()"><div class="kpi-label">Situação</div><div class="kpi-value">${cash?.status==='aberto'?'Aberto':cash?.status==='fechado'?'Fechado':'Não aberto'}</div><div class="kpi-sub">${cashShiftLabelV121(shift)}</div><span class="kpi-arrow">›</span></div><div class="kpi green clickable" onclick="showCashMovesV110()"><div class="kpi-label">Vendas em dinheiro</div><div class="kpi-value">${fmt(metrics.sales)}</div><div class="kpi-sub">Clique para ver movimentos</div><span class="kpi-arrow">›</span></div><div class="kpi orange clickable" onclick="showCashMemoryV110()"><div class="kpi-label">Saldo esperado</div><div class="kpi-value">${fmt(displayExpected)}</div><div class="kpi-sub">Memória de cálculo</div><span class="kpi-arrow">›</span></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="card-head"><div class="card-title">Operação</div></div><div class="card-body">${!cash||cash.status!=='aberto'?(cash?.status==='fechado'?`<div class="alert">Caixa encerrado. O fechamento permanece disponível para consulta e auditoria.</div>${closure}`:`<button class="btn btn-primary" onclick="openCash('${point}','${shift}')">Abrir caixa</button>`):`<div class="fg"><label>Valor contado / devolvido</label><input class="fi" id="cashCounted" placeholder="0,00"></div><button class="btn btn-orange" onclick="openCloseCashReviewV121('${id}',${metrics.expected})">Revisar fechamento</button>`}</div></div><div class="card"><div class="card-head"><div class="card-title">Movimentos</div></div><div>${moves.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Data</th><th>Tipo</th><th>Responsável</th><th style="text-align:right">Valor</th></tr></thead><tbody>${moves.sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm))).map(m=>`<tr><td>${humanDate(m.criadoEm)}</td><td>${esc(statusLabelV120(String(m.tipo||'').replaceAll('_',' ')))}</td><td>${esc(m.usuarioNome||m.usuarioId||'-')}</td><td class="money">${fmt(m.valorCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem movimentos.</div>'}</div></div></div>`
}
window.closeCash=function(id,expected){return openCloseCashReviewV121(id,expected)}
function openCloseCashReviewV121(id,expected){
  const raw=$('#cashCounted')?.value;if(raw==null||String(raw).trim()==='')return appMessage('Informe o valor contado.');const counted=parseBRL(raw),diff=counted-Number(expected||0);state.pendingCashCloseV121={id,expected:Number(expected||0),counted,diff};
  openModal('Revisar fechamento de caixa',`<div class="mini-breakdown"><span><span>Saldo esperado</span><strong>${fmt(expected)}</strong></span><span><span>Valor contado</span><strong>${fmt(counted)}</strong></span><span><span>Diferença</span><strong class="${diff===0?'':'neg'}">${fmt(diff)}</strong></span></div>${diff!==0?`<div class="v121-divergence"><strong>Há divergência no caixa.</strong> A justificativa é obrigatória antes do fechamento.</div><div class="fg" style="margin-top:12px"><label>Justificativa da divergência</label><textarea id="cashJustificationV121" class="fi" rows="4" placeholder="Explique o motivo apurado ou a ocorrência percebida."></textarea></div>`:`<div class="alert" style="margin-top:12px">A contagem confere com o saldo esperado.</div>`}<div class="fg" style="margin-top:12px"><label>Responsável pelo fechamento</label><input class="fi" value="${esc(state.user.nome)}" disabled></div><label class="switch-line" style="margin-top:10px"><span><strong>Confirmo esta conferência</strong><small class="muted">O fechamento ficará identificado com este perfil e horário.</small></span><input id="cashConfirmV121" type="checkbox"></label><button class="btn btn-primary" style="width:100%;margin-top:14px" onclick="confirmCloseCashV121()">Assinar e fechar caixa</button>`)
}
async function confirmCloseCashV121(){
  const p=state.pendingCashCloseV121;if(!p)return;const confirmed=$('#cashConfirmV121')?.checked;if(!confirmed)return appMessage('Confirme a conferência antes de fechar.');const justification=($('#cashJustificationV121')?.value||'').trim();if(p.diff!==0&&!justification)return appMessage('A justificativa é obrigatória quando há divergência.');const now=nowIso(),cashRef=db.collection('caixas').doc(p.id),snap=await cashRef.get();if(!snap.exists)return appMessage('Caixa não encontrado.');const cash={id:p.id,...snap.data()},closeRef=db.collection('fechamentos_caixa').doc(),batch=db.batch();
  batch.set(cashRef,{status:'fechado',valorContadoCentavos:p.counted,valorEsperadoRegistradoCentavos:p.expected,diferencaCentavos:p.diff,justificativaDivergencia:p.diff!==0?justification:null,fechadoPorId:state.user.id,fechadoPorNome:state.user.nome,fechadoEm:now,assinaturaOperacional:{tipo:'perfil_provisorio',usuarioId:state.user.id,nome:state.user.nome,assinadoEm:now},atualizadoEm:now},{merge:true});
  batch.set(closeRef,{id:closeRef.id,caixaId:p.id,ponto:cash.ponto,turno:cash.turno,dataChave:cash.dataChave||dateKey(),valorEsperadoCentavos:p.expected,valorContadoCentavos:p.counted,diferencaCentavos:p.diff,justificativaDivergencia:p.diff!==0?justification:null,fechadoPorId:state.user.id,fechadoPorNome:state.user.nome,fechadoEm:now,assinaturaOperacional:{tipo:'perfil_provisorio',usuarioId:state.user.id,nome:state.user.nome,assinadoEm:now},criadoEm:now});
  const ownMove=db.collection('movimentos_caixa').doc();batch.set(ownMove,{id:ownMove.id,caixaId:p.id,tipo:'fechamento_caixa',valorCentavos:0,usuarioId:state.user.id,usuarioNome:state.user.nome,observacao:p.diff!==0?justification:'Sem divergência',dataChave:cash.dataChave||dateKey(),criadoEm:now});
  if(cash.ponto==='cantina'){
    const returnMove=db.collection('movimentos_caixa').doc();batch.set(returnMove,{id:returnMove.id,caixaId:p.id,tipo:'transferencia_saida_secretaria',valorCentavos:p.counted,origemCaixaId:p.id,destinoPonto:'secretaria',usuarioId:state.user.id,usuarioNome:state.user.nome,dataChave:cash.dataChave||dateKey(),criadoEm:now});
    const transfer=db.collection('transferencias_caixa').doc(),destId=`secretaria_${cash.dataChave||dateKey()}_${cash.turno||'manha'}`,destSnap=await db.collection('caixas').doc(destId).get(),destOpen=destSnap.exists&&destSnap.data().status==='aberto';
    batch.set(transfer,{id:transfer.id,origemCaixaId:p.id,origemPonto:'cantina',destinoPonto:'secretaria',turno:cash.turno||'manha',dataChave:cash.dataChave||dateKey(),valorCentavos:p.counted,status:destOpen?'recebido':'pendente_recebimento',destinoCaixaId:destOpen?destId:null,criadoPorId:state.user.id,criadoPorNome:state.user.nome,criadoEm:now,recebidoEm:destOpen?now:null});
    if(destOpen){const incoming=db.collection('movimentos_caixa').doc();batch.set(incoming,{id:incoming.id,caixaId:destId,tipo:'transferencia_entrada_cantina',valorCentavos:p.counted,origemCaixaId:p.id,transferenciaId:transfer.id,usuarioId:state.user.id,usuarioNome:state.user.nome,dataChave:cash.dataChave||dateKey(),criadoEm:now})}
  }
  await batch.commit();await audit('fechamento_caixa',{caixaId:p.id,contadoCentavos:p.counted,esperadoCentavos:p.expected,diferencaCentavos:p.diff,justificativa:p.diff!==0?justification:null,fechadoPor:state.user.nome});state.pendingCashCloseV121=null;closeModal();await renderCaixa();toast('Caixa fechado e assinado operacionalmente.')
}

async function renderCashManagementV121(){
  const day=state.cashManagerDateV121||dateKey();state.cashManagerDateV121=day;const rows=await cashRowsForDateV121(day),transferDocs=await cashPagedDocsLegacyV221(db.collection('transferencias_caixa').where('dataChave','==',day),100),transfers=transferDocs.map(d=>({id:d.id,...d.data()})),pending=transfers.filter(x=>x.status==='pendente_recebimento'),open=rows.filter(x=>x.cash.status==='aberto').length,closed=rows.filter(x=>x.cash.status==='fechado').length,divs=rows.filter(x=>Number(x.cash.diferencaCentavos||0)!==0).length,totalDiff=rows.reduce((s,x)=>s+Number(x.cash.diferencaCentavos||0),0);
  $('#mainContent').innerHTML=pageHeader('Gestão de caixas','Veja todos os caixas, movimentos, fechamentos, responsáveis e justificativas.')+`<div class="v121-cash-toolbar"><div class="fg"><label>Data</label><input id="cashManagerDateV121" type="date" class="fi" value="${esc(day)}"></div><button class="btn btn-primary" onclick="state.cashManagerDateV121=$('#cashManagerDateV121').value;renderCashManagementV121()">Atualizar</button></div><div class="v121-cash-summary"><div class="kpi"><div class="kpi-label">Caixas encontrados</div><div class="kpi-value">${rows.length}</div></div><div class="kpi green"><div class="kpi-label">Abertos</div><div class="kpi-value">${open}</div></div><div class="kpi orange"><div class="kpi-label">Fechados</div><div class="kpi-value">${closed}</div></div><div class="kpi red"><div class="kpi-label">Com divergência</div><div class="kpi-value">${divs}</div><div class="kpi-sub">Saldo líquido: ${fmt(totalDiff)}</div></div></div>${pending.length?`<div class="alert warn" style="margin-top:14px"><strong>${pending.length} retorno(s) da cantina aguardando recebimento pela secretaria.</strong><br>${pending.map(x=>`${cashShiftLabelV121(x.turno)} · ${fmt(x.valorCentavos)} · enviado por ${esc(x.criadoPorNome||'-')}`).join('<br>')}</div>`:''}<div style="margin-top:14px">${rows.length?rows.map(r=>cashManagerCardV121(r)).join(''):`<div class="card"><div class="card-body"><div class="v121-empty-brand"><img src="${BRAND_V120.icon}" alt=""><span>Nenhum caixa registrado nesta data.</span></div></div></div>`}</div>`
}
function cashManagerCardV121(r){const c=r.cash,m=r.metrics,diff=Number(c.diferencaCentavos||0);return `<div class="v121-cash-card" style="margin-bottom:12px"><div class="v121-cash-card-head"><div><strong>${esc(cashPointLabelV121(c.ponto))} · ${esc(cashShiftLabelV121(c.turno))}</strong><div class="muted" style="margin-top:4px">Aberto por ${esc(c.operadorNome||c.operadorId||'-')} ${c.abertoEm?`· ${humanDate(c.abertoEm)}`:''}</div></div><span class="badge ${c.status==='aberto'?'b-green':'b-blue'}">${esc(c.status||'-')}</span></div><div class="v121-cash-card-body"><div class="v121-cash-metrics"><div class="v121-cash-metric"><span>Vendas dinheiro</span><strong>${fmt(m.sales)}</strong></div><div class="v121-cash-metric"><span>Esperado</span><strong>${fmt(c.valorEsperadoRegistradoCentavos??m.expected)}</strong></div><div class="v121-cash-metric"><span>Contado</span><strong>${c.valorContadoCentavos!=null?fmt(c.valorContadoCentavos):'—'}</strong></div></div>${c.status==='fechado'?`<div class="v121-signature"><strong>Assinatura operacional:</strong> ${esc(c.fechadoPorNome||c.assinaturaOperacional?.nome||'-')} · ${c.fechadoEm?humanDate(c.fechadoEm):'-'}<br><strong>Diferença:</strong> <span class="${diff===0?'':'neg'}">${fmt(diff)}</span>${diff!==0?`<div class="v121-justification"><strong>Justificativa:</strong> ${esc(c.justificativaDivergencia||'Não informada')}</div>`:''}</div>`:''}<div class="actions" style="margin-top:12px"><button class="btn btn-light" onclick="openCashDetailV121('${c.id}')">Ver movimentação completa</button></div></div></div>`}
async function openCashDetailV121(id){
  const snap=await db.collection('caixas').doc(id).get();if(!snap.exists)return;const c={id,...snap.data()},moveDocs=await cashPagedDocsLegacyV221(db.collection('movimentos_caixa').where('caixaId','==',id),250),moves=moveDocs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.criadoEm).localeCompare(String(b.criadoEm))),metrics=cashMetricsV121(c,moves);state.currentCashReportV110={cash:c,moves,point:c.ponto,shift:c.turno,...metrics};
  openModal(`Caixa · ${cashPointLabelV121(c.ponto)} · ${cashShiftLabelV121(c.turno)}`,`<div class="mini-breakdown"><span><span>Saldo inicial</span><strong>${fmt(metrics.initial)}</strong></span><span><span>Vendas em dinheiro</span><strong>${fmt(metrics.sales)}</strong></span><span><span>Saldo esperado</span><strong>${fmt(c.valorEsperadoRegistradoCentavos??metrics.expected)}</strong></span>${c.valorContadoCentavos!=null?`<span><span>Saldo contado</span><strong>${fmt(c.valorContadoCentavos)}</strong></span><span><span>Diferença</span><strong>${fmt(c.diferencaCentavos)}</strong></span>`:''}</div>${c.status==='fechado'?`<div class="v121-signature"><strong>Assinatura operacional:</strong> ${esc(c.fechadoPorNome||c.assinaturaOperacional?.nome||'-')}<br><strong>Data e hora:</strong> ${c.fechadoEm?humanDate(c.fechadoEm):'-'}${Number(c.diferencaCentavos||0)!==0?`<div class="v121-justification"><strong>Justificativa:</strong><br>${esc(c.justificativaDivergencia||'Não informada')}</div>`:''}</div>`:''}<div class="actions" style="margin:14px 0"><button class="btn btn-primary" onclick="downloadCashPdfV110()">Baixar relatório PDF</button></div>${moves.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Responsável</th><th>Observação</th><th style="text-align:right">Valor</th></tr></thead><tbody>${moves.map(m=>`<tr><td>${humanDate(m.criadoEm)}</td><td>${esc(String(m.tipo||'').replaceAll('_',' '))}</td><td>${esc(m.usuarioNome||m.usuarioId||'-')}</td><td>${esc(m.observacao||'-')}</td><td class="money">${fmt(m.valorCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem movimentos.</div>'}`)
}

/* ---------- Relatório de caixa com marca, assinatura e justificativa ---------- */
window.downloadCashPdfV110=async function(){
  const r=state.currentCashReportV110;if(!r?.cash)return;const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'}),c=r.cash;let y=await drawPdfBrandHeaderV121(pdf,'Fechamento de caixa',`${cashPointLabelV121(r.point)} · ${cashShiftLabelV121(r.shift)} · ${c.dataChave||dateKey()}`);
  const lines=[['Saldo inicial',r.initial],['Vendas em dinheiro',r.sales],['Saldo esperado',c.valorEsperadoRegistradoCentavos??r.expected],['Saldo contado',c.valorContadoCentavos],['Diferença',c.diferencaCentavos]];pdf.setTextColor(30);pdf.setFontSize(10);for(const [label,val] of lines){if(val==null)continue;pdf.setDrawColor(225);pdf.line(15,y+6,195,y+6);pdf.setFont('helvetica','normal');pdf.text(label,17,y+4);pdf.setFont('helvetica','bold');pdf.text(fmt(val).replace(/\u00a0/g,' '),193,y+4,{align:'right'});y+=9}
  y+=6;pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.text('FECHAMENTO E RESPONSABILIDADE',15,y);y+=7;pdf.setTextColor(30);pdf.setFont('helvetica','normal');pdf.text(`Aberto por: ${c.operadorNome||c.operadorId||'-'}`,17,y);y+=5;pdf.text(`Assinatura operacional: ${c.fechadoPorNome||c.assinaturaOperacional?.nome||'-'}`,17,y);y+=5;pdf.text(`Fechado em: ${c.fechadoEm?humanDate(c.fechadoEm):'-'}`,17,y);y+=7;if(Number(c.diferencaCentavos||0)!==0){pdf.setFillColor(255,248,236);const just=pdf.splitTextToSize(`Justificativa da divergência: ${c.justificativaDivergencia||'Não informada'}`,172),h=just.length*4.5+8;pdf.roundedRect(15,y,180,h,2,2,'F');pdf.setTextColor(110,72,15);pdf.text(just,19,y+6);y+=h+7}
  pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.text('MOVIMENTOS',15,y);y+=7;pdf.setTextColor(30);pdf.setFont('helvetica','normal');for(const m of [...(r.moves||[])].sort((a,b)=>String(a.criadoEm).localeCompare(String(b.criadoEm)))){if(y>274){pdf.addPage();y=await drawPdfContinuationHeaderV121(pdf,'Fechamento de caixa')}pdf.setFontSize(8.5);pdf.text(humanDate(m.criadoEm),15,y);pdf.text(pdf.splitTextToSize(String(m.tipo||'').replaceAll('_',' '),62),55,y);pdf.text(fmt(m.valorCentavos).replace(/\u00a0/g,' '),193,y,{align:'right'});y+=6}
  pdf.save(`fechamento-caixa-${r.point}-${c.dataChave||dateKey()}.pdf`)
}

/* Atualiza versão sem reinicializar dados. */
/* atualização de versão herdada removida pela V1.5.0-dev2 */



/* Recebe automaticamente retornos pendentes quando o caixa da secretaria é aberto. */
const ensureCashSessionBaseV121=window.ensureCashSession;
window.ensureCashSession=async function(point){
  const cash=await ensureCashSessionBaseV121(point);if(point!=='secretaria'||!cash?.id)return cash;
  const day=cash.dataChave||dateKey(),transferRows=await cashPagedDocsLegacyV221(db.collection('transferencias_caixa').where('dataChave','==',day),200),pending=transferRows.map(x=>({id:x.id,ref:db.collection('transferencias_caixa').doc(x.id),...x})).filter(x=>x.status==='pendente_recebimento'&&x.destinoPonto==='secretaria'&&(!x.turno||x.turno===cash.turno));
  if(!pending.length)return cash;const batch=db.batch(),now=nowIso();for(const tr of pending){const mov=db.collection('movimentos_caixa').doc();batch.set(mov,{id:mov.id,caixaId:cash.id,tipo:'transferencia_entrada_cantina',valorCentavos:Number(tr.valorCentavos||0),origemCaixaId:tr.origemCaixaId||null,transferenciaId:tr.id,usuarioId:state.user.id,usuarioNome:state.user.nome,dataChave:day,criadoEm:now});batch.set(tr.ref,{status:'recebido',destinoCaixaId:cash.id,recebidoPorId:state.user.id,recebidoPorNome:state.user.nome,recebidoEm:now,atualizadoEm:now},{merge:true})}await batch.commit();await audit('retornos_cantina_recebidos',{caixaId:cash.id,quantidade:pending.length,valorCentavos:pending.reduce((s,x)=>s+Number(x.valorCentavos||0),0)});return cash
}



/* =========================================================
   Escola Piaget — V1.2.3
   Correção estrutural do caixa:
   - cada abertura cria uma sessão independente;
   - sessão fechada não recebe novos movimentos;
   - dinheiro exige sessão previamente aberta e conferida;
   - múltiplas aberturas/fechamentos no mesmo turno;
   - gestão consolida sessões e mantém caixas antigos para consulta.
   ========================================================= */
const V123_VERSION='1.2.3-dev';
const CASH_SESSIONS_V123='sessoes_caixa';
async function cashPagedDocsLegacyV221(query,pageSize=200){const out=[];let cursor=null;while(true){let q=query.limit(pageSize);if(cursor)q=q.startAfter(cursor);const snap=await q.get();out.push(...snap.docs);if(snap.size<pageSize)break;cursor=snap.docs[snap.docs.length-1]}return out}

function cashContextV123(pointOverride=null,shiftOverride=null){
  const point=pointOverride||(state.user?.perfil==='cantina'?'cantina':'secretaria');
  const shift=shiftOverride||(point==='cantina'?(state.recessGroup==='tarde'?'tarde':'manha'):(state.user?.turnos?.[0]||'manha'));
  return{point,shift,day:dateKey()}
}
async function cashSessionsForDayV123(day=dateKey()){
  const docs=await cashPagedDocsLegacyV221(db.collection(CASH_SESSIONS_V123).where('dataChave','==',day),100);
  return docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.abertoEm||b.criadoEm||'').localeCompare(String(a.abertoEm||a.criadoEm||'')))
}
async function openCashSessionV123(point,shift,day=dateKey()){
  const rows=await cashSessionsForDayV123(day);return rows.find(x=>x.ponto===point&&x.turno===shift&&x.status==='aberto')||null
}
async function sessionMovesV123(id){
  const docs=await cashPagedDocsLegacyV221(db.collection('movimentos_caixa').where('caixaId','==',id),250);
  return docs.map(d=>({id:d.id,...d.data()}))
}
async function latestSessionV123(point,shift,day=dateKey()){
  const rows=(await cashSessionsForDayV123(day)).filter(x=>x.ponto===point&&x.turno===shift);return rows[0]||null
}
function cashSessionLabelV123(s){return `Sessão #${String(Number(s?.numeroSessao||0)).padStart(3,'0')}`}
function cashStatusFlagHtmlV123(session,point,shift){
  if(session)return `<div class="cash-status-v123 open" id="cashStatusFlagV123"><div class="left"><span class="dot"></span><div><strong>Caixa físico aberto · ${cashPointLabelV121(point)} ${cashShiftLabelV121(shift)}</strong><small>${cashSessionLabelV123(session)} · aberto por ${esc(session.abertoPorNome||session.operadorNome||'-')} às ${session.abertoEm?humanDate(session.abertoEm):'-'} · saldo inicial ${fmt(session.valorInicialCentavos||0)}</small></div></div><button class="btn btn-light" onclick="navigate('caixa')">Ver caixa</button></div>`;
  return `<div class="cash-status-v123 closed" id="cashStatusFlagV123"><div class="left"><span class="dot"></span><div><strong>Caixa físico ainda não foi aberto</strong><small>Vendas e recebimentos em dinheiro estão bloqueados até a contagem de abertura.</small></div></div><button class="btn btn-primary" onclick="openCash('${point}','${shift}')">Abrir e conferir caixa</button></div>`
}
async function refreshCashStatusV123(pointOverride=null,shiftOverride=null){
  const c=cashContextV123(pointOverride,shiftOverride),session=await openCashSessionV123(c.point,c.shift,c.day);state.cashStatusV123={...c,session};return state.cashStatusV123
}

/* Nunca mais abre caixa automaticamente. Retorna apenas sessão já aberta. */
window.ensureCashSession=async function(point){
  const c=cashContextV123(point),session=await openCashSessionV123(c.point,c.shift,c.day);
  if(!session){const e=new Error(`Caixa físico não aberto para ${cashPointLabelV121(c.point)} · ${cashShiftLabelV121(c.shift)}. Abra e confira o caixa antes de movimentar dinheiro.`);e.code='cash/not-open';throw e}
  return session
};

/* Abertura consciente: sempre cria nova sessão. */
window.openCash=async function(point,shift){
  const c=cashContextV123(point,shift),existing=await openCashSessionV123(c.point,c.shift,c.day);
  if(existing)return appMessage(`${cashSessionLabelV123(existing)} já está aberta para ${cashPointLabelV121(c.point)} · ${cashShiftLabelV121(c.shift)}.`);
  const last=await latestSessionV123(c.point,c.shift,c.day);state.pendingCashOpenV123=c;
  openModal('Abrir nova sessão de caixa',`<div class="alert">Cada abertura cria uma sessão independente. Antes de vender em dinheiro, conte o valor físico existente no caixa.</div><div class="mini-breakdown" style="margin-top:12px"><span><span>Ponto</span><strong>${cashPointLabelV121(c.point)}</strong></span><span><span>Turno</span><strong>${cashShiftLabelV121(c.shift)}</strong></span><span><span>Responsável</span><strong>${esc(state.user?.nome||'-')}</strong></span></div>${last?`<div class="alert" style="margin-top:12px">Última sessão: <strong>${cashSessionLabelV123(last)}</strong> · ${esc(last.status||'-')}${last.valorContadoCentavos!=null?` · última contagem ${fmt(last.valorContadoCentavos)}`:''}. Esse valor é apenas referência e não será reaproveitado automaticamente.</div>`:''}<div class="fg" style="margin-top:14px"><label>Valor físico contado na abertura</label><input id="cashOpenAmountV123" class="fi" inputmode="decimal" placeholder="0,00" autofocus></div><label class="switch-line" style="margin-top:10px"><span><strong>Confirmo a contagem de abertura</strong><small class="muted">A sessão ficará identificada com meu perfil e horário.</small></span><input id="cashOpenConfirmV123" type="checkbox"></label><button class="btn btn-primary" style="width:100%;margin-top:14px" onclick="confirmOpenCashV123()">Confirmar e abrir nova sessão</button>`)
};
async function confirmOpenCashV123(){
  const c=state.pendingCashOpenV123;if(!c)return;const raw=$('#cashOpenAmountV123')?.value;
  if(raw==null||String(raw).trim()==='')return appMessage('Informe o valor físico contado na abertura.');
  if(!$('#cashOpenConfirmV123')?.checked)return appMessage('Confirme a contagem de abertura.');
  const initial=parseBRL(raw);if(initial<0)return appMessage('O valor de abertura não pode ser negativo.');
  const existing=await openCashSessionV123(c.point,c.shift,c.day);if(existing)return appMessage('Já existe uma sessão aberta para este ponto e turno.');
  const same=(await cashSessionsForDayV123(c.day)).filter(x=>x.ponto===c.point&&x.turno===c.shift),number=same.reduce((m,x)=>Math.max(m,Number(x.numeroSessao||0)),0)+1,ref=db.collection(CASH_SESSIONS_V123).doc(),mov=db.collection('movimentos_caixa').doc(),now=nowIso();
  const batch=db.batch();batch.set(ref,{id:ref.id,numeroSessao:number,ponto:c.point,turno:c.shift,dataChave:c.day,status:'aberto',valorInicialCentavos:initial,saldoInicialContadoCentavos:initial,abertoPorId:state.user.id,abertoPorNome:state.user.nome,operadorId:state.user.id,operadorNome:state.user.nome,abertoEm:now,criadoEm:now,atualizadoEm:now,schemaVersion:4});
  batch.set(mov,{id:mov.id,caixaId:ref.id,sessaoCaixaId:ref.id,tipo:'abertura_caixa',valorCentavos:initial,usuarioId:state.user.id,usuarioNome:state.user.nome,observacao:`Saldo inicial contado: ${fmt(initial)}`,dataChave:c.day,criadoEm:now});
  /* Retornos pendentes da cantina entram na nova sessão da secretaria. */
  let pending=[];if(c.point==='secretaria'){
    const transferDocs=await cashPagedDocsLegacyV221(db.collection('transferencias_caixa').where('dataChave','==',c.day),100);pending=transferDocs.map(d=>({id:d.id,ref:d.ref,...d.data()})).filter(x=>x.status==='pendente_recebimento'&&x.destinoPonto==='secretaria'&&(!x.turno||x.turno===c.shift));
    for(const tr of pending){const im=db.collection('movimentos_caixa').doc();batch.set(im,{id:im.id,caixaId:ref.id,sessaoCaixaId:ref.id,tipo:'transferencia_entrada_cantina',valorCentavos:Number(tr.valorCentavos||0),origemCaixaId:tr.origemCaixaId||null,transferenciaId:tr.id,usuarioId:state.user.id,usuarioNome:state.user.nome,dataChave:c.day,criadoEm:now});batch.set(tr.ref,{status:'recebido',destinoCaixaId:ref.id,destinoSessaoCaixaId:ref.id,recebidoPorId:state.user.id,recebidoPorNome:state.user.nome,recebidoEm:now,atualizadoEm:now},{merge:true})}
  }
  await batch.commit();await audit('abertura_sessao_caixa',{sessaoCaixaId:ref.id,ponto:c.point,turno:c.shift,numeroSessao:number,valorInicialCentavos:initial,retornosRecebidos:pending.length});state.pendingCashOpenV123=null;closeModal();toast(`${cashSessionLabelV123({numeroSessao:number})} aberta.`);
  if(state.currentPage==='vendas')await renderSalesWorkspaceV110();else if(state.currentPage==='atendimento')await renderAtendimento();else await renderCaixa()
}

/* Fechamento usa a sessão nova e torna-a definitivamente histórica. */
window.openCloseCashReviewV121=function(id,expected){
  const raw=$('#cashCounted')?.value;if(raw==null||String(raw).trim()==='')return appMessage('Informe o valor contado.');const counted=parseBRL(raw),diff=counted-Number(expected||0);state.pendingCashCloseV121={id,expected:Number(expected||0),counted,diff,collection:CASH_SESSIONS_V123};
  openModal('Revisar fechamento de caixa',`<div class="mini-breakdown"><span><span>Saldo esperado</span><strong>${fmt(expected)}</strong></span><span><span>Valor contado</span><strong>${fmt(counted)}</strong></span><span><span>Diferença</span><strong class="${diff===0?'':'neg'}">${fmt(diff)}</strong></span></div>${diff!==0?`<div class="v121-divergence"><strong>Há divergência no caixa.</strong> A justificativa é obrigatória antes do fechamento.</div><div class="fg" style="margin-top:12px"><label>Justificativa da divergência</label><textarea id="cashJustificationV121" class="fi" rows="4" placeholder="Explique o motivo apurado ou a ocorrência percebida."></textarea></div>`:`<div class="alert" style="margin-top:12px">A contagem confere com o saldo esperado.</div>`}<div class="fg" style="margin-top:12px"><label>Responsável pelo fechamento</label><input class="fi" value="${esc(state.user.nome)}" disabled></div><label class="switch-line" style="margin-top:10px"><span><strong>Confirmo esta conferência</strong><small class="muted">Esta sessão será encerrada e não receberá novos movimentos.</small></span><input id="cashConfirmV121" type="checkbox"></label><button class="btn btn-primary" style="width:100%;margin-top:14px" onclick="confirmCloseCashV121()">Assinar e fechar sessão</button>`)
};
window.closeCash=function(id,expected){return openCloseCashReviewV121(id,expected)};
window.confirmCloseCashV121=async function(){
  const p=state.pendingCashCloseV121;if(!p)return;if(!$('#cashConfirmV121')?.checked)return appMessage('Confirme a conferência antes de fechar.');let justification=($('#cashJustificationV121')?.value||'').trim();
  const ref=db.collection(CASH_SESSIONS_V123).doc(p.id),snap=await ref.get();if(!snap.exists)return appMessage('Sessão de caixa não encontrada.');const cash={id:p.id,...snap.data()};if(cash.status!=='aberto')return appMessage('Esta sessão já está fechada e não pode receber novo fechamento.');
  const moves=await sessionMovesV123(p.id),actualExpected=cashMetricsV121(cash,moves).expected,diff=p.counted-actualExpected;if(diff!==0&&!justification)return appMessage('A justificativa é obrigatória quando há divergência.');
  const now=nowIso(),closeRef=db.collection('fechamentos_caixa').doc(),batch=db.batch();batch.set(ref,{status:'fechado',valorContadoCentavos:p.counted,valorEsperadoRegistradoCentavos:actualExpected,diferencaCentavos:diff,justificativaDivergencia:diff!==0?justification:null,fechadoPorId:state.user.id,fechadoPorNome:state.user.nome,fechadoEm:now,assinaturaOperacional:{tipo:'perfil_provisorio',usuarioId:state.user.id,nome:state.user.nome,assinadoEm:now},atualizadoEm:now},{merge:true});
  batch.set(closeRef,{id:closeRef.id,caixaId:p.id,sessaoCaixaId:p.id,numeroSessao:cash.numeroSessao||null,ponto:cash.ponto,turno:cash.turno,dataChave:cash.dataChave||dateKey(),valorEsperadoCentavos:actualExpected,valorContadoCentavos:p.counted,diferencaCentavos:diff,justificativaDivergencia:diff!==0?justification:null,fechadoPorId:state.user.id,fechadoPorNome:state.user.nome,fechadoEm:now,assinaturaOperacional:{tipo:'perfil_provisorio',usuarioId:state.user.id,nome:state.user.nome,assinadoEm:now},criadoEm:now,schemaVersion:4});
  const ownMove=db.collection('movimentos_caixa').doc();batch.set(ownMove,{id:ownMove.id,caixaId:p.id,sessaoCaixaId:p.id,tipo:'fechamento_caixa',valorCentavos:0,usuarioId:state.user.id,usuarioNome:state.user.nome,observacao:diff!==0?justification:'Sem divergência',dataChave:cash.dataChave||dateKey(),criadoEm:now});
  if(cash.ponto==='cantina'&&p.counted>0){
    const destOpen=await openCashSessionV123('secretaria',cash.turno||'manha',cash.dataChave||dateKey()),returnMove=db.collection('movimentos_caixa').doc(),transfer=db.collection('transferencias_caixa').doc();batch.set(returnMove,{id:returnMove.id,caixaId:p.id,sessaoCaixaId:p.id,tipo:'transferencia_saida_secretaria',valorCentavos:p.counted,origemCaixaId:p.id,origemSessaoCaixaId:p.id,destinoPonto:'secretaria',usuarioId:state.user.id,usuarioNome:state.user.nome,dataChave:cash.dataChave||dateKey(),criadoEm:now});
    batch.set(transfer,{id:transfer.id,origemCaixaId:p.id,origemSessaoCaixaId:p.id,origemPonto:'cantina',destinoPonto:'secretaria',turno:cash.turno||'manha',dataChave:cash.dataChave||dateKey(),valorCentavos:p.counted,status:destOpen?'recebido':'pendente_recebimento',destinoCaixaId:destOpen?.id||null,destinoSessaoCaixaId:destOpen?.id||null,criadoPorId:state.user.id,criadoPorNome:state.user.nome,criadoEm:now,recebidoEm:destOpen?now:null});
    if(destOpen){const incoming=db.collection('movimentos_caixa').doc();batch.set(incoming,{id:incoming.id,caixaId:destOpen.id,sessaoCaixaId:destOpen.id,tipo:'transferencia_entrada_cantina',valorCentavos:p.counted,origemCaixaId:p.id,origemSessaoCaixaId:p.id,transferenciaId:transfer.id,usuarioId:state.user.id,usuarioNome:state.user.nome,dataChave:cash.dataChave||dateKey(),criadoEm:now})}
  }
  await batch.commit();await audit('fechamento_sessao_caixa',{sessaoCaixaId:p.id,numeroSessao:cash.numeroSessao||null,contadoCentavos:p.counted,esperadoCentavos:actualExpected,diferencaCentavos:diff,justificativa:diff!==0?justification:null,fechadoPor:state.user.nome});state.pendingCashCloseV121=null;closeModal();toast('Sessão fechada e assinada. Para continuar em dinheiro, abra uma nova sessão.');await renderCaixa()
};

/* Render operacional com múltiplas sessões. */
async function renderOperationalCashV123(){
  const c=cashContextV123(),all=(await cashSessionsForDayV123(c.day)).filter(x=>x.ponto===c.point&&x.turno===c.shift),open=all.find(x=>x.status==='aberto')||null,selected=open||all[0]||null,moves=selected?await sessionMovesV123(selected.id):[],metrics=cashMetricsV121(selected,moves),displayExpected=selected?.valorEsperadoRegistradoCentavos??metrics.expected;state.currentCashReportV110=selected?{cash:selected,moves,point:c.point,shift:c.shift,...metrics,expected:displayExpected}:null;
  const currentHtml=open?`<div class="cash-open-card-v123"><div class="muted">${cashSessionLabelV123(open)} · ${cashPointLabelV121(c.point)} ${cashShiftLabelV121(c.shift)}</div><div class="big">Caixa aberto</div><div class="muted">Aberto por ${esc(open.abertoPorNome||'-')} · ${open.abertoEm?humanDate(open.abertoEm):'-'}</div><div class="mini"><div><span>Saldo inicial</span><strong>${fmt(metrics.initial)}</strong></div><div><span>Vendas dinheiro</span><strong>${fmt(metrics.sales)}</strong></div><div><span>Esperado agora</span><strong>${fmt(metrics.expected)}</strong></div></div></div><div class="fg" style="margin-top:15px"><label>Valor físico contado no fechamento</label><input class="fi" id="cashCounted" placeholder="0,00" inputmode="decimal"></div><button class="btn btn-orange" style="width:100%" onclick="openCloseCashReviewV121('${open.id}',${metrics.expected})">Revisar e fechar esta sessão</button>`:`<div class="alert warn"><strong>Nenhuma sessão aberta.</strong><br>Vendas em dinheiro ficam bloqueadas até uma nova contagem de abertura.</div><button class="btn btn-primary" style="width:100%;margin-top:12px" onclick="openCash('${c.point}','${c.shift}')">+ Abrir nova sessão</button>${selected?`<div class="v121-signature" style="margin-top:14px"><strong>Última sessão:</strong> ${cashSessionLabelV123(selected)} · ${esc(selected.status||'-')}<br><strong>Fechada por:</strong> ${esc(selected.fechadoPorNome||'-')} ${selected.fechadoEm?`· ${humanDate(selected.fechadoEm)}`:''}${Number(selected.diferencaCentavos||0)!==0?`<div class="v121-justification"><strong>Justificativa:</strong> ${esc(selected.justificativaDivergencia||'Não informada')}</div>`:''}</div>`:''}`;
  $('#mainContent').innerHTML=pageHeader(`Caixa da ${cashPointLabelV121(c.point)}`,'Cada abertura cria uma sessão independente. Fechar é conferir e encerrar definitivamente aquela sessão.',selected?`<button class="btn btn-outline" onclick="downloadCashPdfV110()">Relatório da sessão</button>`:'')+cashStatusFlagHtmlV123(open,c.point,c.shift)+`<div class="grid g2"><div class="card"><div class="card-head"><div class="card-title">Sessão atual</div></div><div class="card-body">${currentHtml}</div></div><div class="card"><div class="card-head"><div class="card-title">Movimentos da sessão exibida</div></div><div>${moves.length?`<div class="table-wrap" style="border:0"><table><thead><tr><th>Data</th><th>Tipo</th><th>Responsável</th><th style="text-align:right">Valor</th></tr></thead><tbody>${moves.sort((a,b)=>String(b.criadoEm).localeCompare(String(a.criadoEm))).map(m=>`<tr><td>${humanDate(m.criadoEm)}</td><td>${esc(statusLabelV120(String(m.tipo||'').replaceAll('_',' ')))}</td><td>${esc(m.usuarioNome||m.usuarioId||'-')}</td><td class="money">${fmt(m.valorCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem movimentos nesta sessão.</div>'}</div></div></div><div class="card" style="margin-top:14px"><div class="card-head"><div class="card-title">Sessões de hoje · ${cashShiftLabelV121(c.shift)}</div><span class="badge b-blue">${all.length}</span></div><div class="card-body"><div class="cash-session-list-v123">${all.length?all.map(s=>`<div class="cash-session-row-v123"><div><span class="cash-session-number-v123">#${String(Number(s.numeroSessao||0)).padStart(3,'0')}</span><strong>${s.status==='aberto'?'Aberta':'Fechada'}</strong><div class="meta">${s.abertoEm?humanDate(s.abertoEm):'-'}${s.fechadoEm?` → ${humanDate(s.fechadoEm)}`:' → em andamento'} · ${esc(s.abertoPorNome||'-')}</div></div><div class="right"><span class="badge ${s.status==='aberto'?'b-green':'b-blue'}">${esc(s.status)}</span><div style="margin-top:7px"><button class="btn btn-light" onclick="openCashDetailV123('${s.id}')">Ver sessão</button></div></div></div>`).join(''):'<div class="empty">Nenhuma sessão criada hoje.</div>'}</div></div></div>`
}

/* Gestão: novas sessões + caixas antigos somente como histórico legado. */
async function cashRowsSessionsV123(day){
  const sessions=await cashSessionsForDayV123(day);return Promise.all(sessions.map(async cash=>{const moves=await sessionMovesV123(cash.id);return{cash,moves,metrics:cashMetricsV121(cash,moves),source:'session'}}))
}
window.renderCashManagementV121=async function(){
  const day=state.cashManagerDateV121||dateKey();state.cashManagerDateV121=day;const sessionRows=await cashRowsSessionsV123(day),legacyRows=await cashRowsForDateV121(day),legacy=legacyRows.map(x=>({...x,source:'legacy'})),rows=[...sessionRows,...legacy].sort((a,b)=>String(b.cash.abertoEm||b.cash.criadoEm||'').localeCompare(String(a.cash.abertoEm||a.cash.criadoEm||''))),transferDocs=await cashPagedDocsLegacyV221(db.collection('transferencias_caixa').where('dataChave','==',day),100),transfers=transferDocs.map(d=>({id:d.id,...d.data()})),pending=transfers.filter(x=>x.status==='pendente_recebimento'),open=sessionRows.filter(x=>x.cash.status==='aberto').length,closed=sessionRows.filter(x=>x.cash.status==='fechado').length,divs=rows.filter(x=>Number(x.cash.diferencaCentavos||0)!==0).length,totalDiff=rows.reduce((s,x)=>s+Number(x.cash.diferencaCentavos||0),0);
  $('#mainContent').innerHTML=pageHeader('Gestão de caixas','Acompanhe cada sessão, responsáveis, divergências e justificativas. Caixas antigos permanecem apenas para consulta.')+`<div class="v121-cash-toolbar"><div class="fg"><label>Data</label><input id="cashManagerDateV121" type="date" class="fi" value="${esc(day)}"></div><button class="btn btn-primary" onclick="state.cashManagerDateV121=$('#cashManagerDateV121').value;renderCashManagementV121()">Atualizar</button></div><div class="v121-cash-summary"><div class="kpi"><div class="kpi-label">Sessões novas</div><div class="kpi-value">${sessionRows.length}</div></div><div class="kpi green"><div class="kpi-label">Abertas agora</div><div class="kpi-value">${open}</div></div><div class="kpi orange"><div class="kpi-label">Fechadas</div><div class="kpi-value">${closed}</div></div><div class="kpi red"><div class="kpi-label">Com divergência</div><div class="kpi-value">${divs}</div><div class="kpi-sub">Saldo líquido: ${fmt(totalDiff)}</div></div></div>${pending.length?`<div class="alert warn" style="margin-top:14px"><strong>${pending.length} retorno(s) da cantina aguardando uma sessão aberta na secretaria.</strong><br>${pending.map(x=>`${cashShiftLabelV121(x.turno)} · ${fmt(x.valorCentavos)} · enviado por ${esc(x.criadoPorNome||'-')}`).join('<br>')}</div>`:''}${legacy.length?`<div class="alert" style="margin-top:14px">Há ${legacy.length} caixa(s) do modelo antigo nesta data. Eles seguem disponíveis como histórico e não serão reutilizados para novas vendas.</div>`:''}<div style="margin-top:14px">${rows.length?rows.map(r=>cashManagerCardV123(r)).join(''):`<div class="card"><div class="card-body"><div class="v121-empty-brand"><img src="${BRAND_V122.light}" alt=""><span>Nenhum caixa registrado nesta data.</span></div></div></div>`}</div>`
};
function cashManagerCardV123(r){const c=r.cash,m=r.metrics,diff=Number(c.diferencaCentavos||0),legacy=r.source==='legacy';return `<div class="v121-cash-card"><div class="v121-cash-card-top"><div><strong>${cashPointLabelV121(c.ponto)} · ${cashShiftLabelV121(c.turno)} ${!legacy&&c.numeroSessao?`· ${cashSessionLabelV123(c)}`:''}</strong><div class="muted">Aberto por ${esc(c.abertoPorNome||c.operadorNome||c.operadorId||'-')} ${c.abertoEm?`· ${humanDate(c.abertoEm)}`:''}</div>${legacy?'<div class="legacy-note-v123">Histórico do modelo antigo de caixa</div>':''}</div><span class="badge ${c.status==='aberto'?'b-green':'b-blue'}">${esc(c.status||'-')}</span></div><div class="v121-cash-card-body"><div class="v121-cash-metrics"><div class="v121-cash-metric"><span>Vendas dinheiro</span><strong>${fmt(m.sales)}</strong></div><div class="v121-cash-metric"><span>Esperado</span><strong>${fmt(c.valorEsperadoRegistradoCentavos??m.expected)}</strong></div><div class="v121-cash-metric"><span>Contado</span><strong>${c.valorContadoCentavos!=null?fmt(c.valorContadoCentavos):'—'}</strong></div></div>${c.status==='fechado'?`<div class="v121-signature"><strong>Assinatura operacional:</strong> ${esc(c.fechadoPorNome||c.assinaturaOperacional?.nome||'-')} · ${c.fechadoEm?humanDate(c.fechadoEm):'-'}<br><strong>Diferença:</strong> <span class="${diff===0?'':'neg'}">${fmt(diff)}</span>${diff!==0?`<div class="v121-justification"><strong>Justificativa:</strong> ${esc(c.justificativaDivergencia||'Não informada')}</div>`:''}</div>`:''}<div class="actions" style="margin-top:12px"><button class="btn btn-light" onclick="${legacy?`openCashDetailV123('${c.id}','legacy')`:`openCashDetailV123('${c.id}')`}">Ver movimentação completa</button></div></div></div>`}
window.openCashDetailV123=async function(id,source='session'){
  const collection=source==='legacy'?'caixas':CASH_SESSIONS_V123,snap=await db.collection(collection).doc(id).get();if(!snap.exists)return;const c={id,...snap.data()},moves=await sessionMovesV123(id),metrics=cashMetricsV121(c,moves);state.currentCashReportV110={cash:c,moves,point:c.ponto,shift:c.turno,...metrics,expected:c.valorEsperadoRegistradoCentavos??metrics.expected};
  openModal(`${source==='legacy'?'Caixa antigo':'Sessão de caixa'} · ${cashPointLabelV121(c.ponto)} · ${cashShiftLabelV121(c.turno)}`,`${source==='legacy'?'<div class="alert">Registro histórico do modelo antigo. Não recebe novos movimentos.</div>':''}<div class="mini-breakdown"><span><span>Saldo inicial</span><strong>${fmt(metrics.initial)}</strong></span><span><span>Vendas em dinheiro</span><strong>${fmt(metrics.sales)}</strong></span><span><span>Saldo esperado</span><strong>${fmt(c.valorEsperadoRegistradoCentavos??metrics.expected)}</strong></span>${c.valorContadoCentavos!=null?`<span><span>Saldo contado</span><strong>${fmt(c.valorContadoCentavos)}</strong></span><span><span>Diferença</span><strong>${fmt(c.diferencaCentavos)}</strong></span>`:''}</div>${c.status==='fechado'?`<div class="v121-signature"><strong>Assinatura operacional:</strong> ${esc(c.fechadoPorNome||c.assinaturaOperacional?.nome||'-')}<br><strong>Data e hora:</strong> ${c.fechadoEm?humanDate(c.fechadoEm):'-'}${Number(c.diferencaCentavos||0)!==0?`<div class="v121-justification"><strong>Justificativa:</strong><br>${esc(c.justificativaDivergencia||'Não informada')}</div>`:''}</div>`:''}<div class="actions" style="margin:14px 0"><button class="btn btn-primary" onclick="downloadCashPdfV110()">Baixar relatório PDF</button></div>${moves.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Responsável</th><th>Observação</th><th style="text-align:right">Valor</th></tr></thead><tbody>${moves.sort((a,b)=>String(a.criadoEm).localeCompare(String(b.criadoEm))).map(m=>`<tr><td>${humanDate(m.criadoEm)}</td><td>${esc(String(m.tipo||'').replaceAll('_',' '))}</td><td>${esc(m.usuarioNome||m.usuarioId||'-')}</td><td>${esc(m.observacao||'-')}</td><td class="money">${fmt(m.valorCentavos)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem movimentos.</div>'}`)
};
window.openCashDetailV121=function(id){return openCashDetailV123(id,'legacy')};
window.renderCaixa=async function(){if(state.user?.perfil==='gestao')return renderCashManagementV121();return renderOperationalCashV123()};

/* Flags e bloqueios na venda da secretaria. */
const _renderSalesWorkspaceV123=window.renderSalesWorkspaceV110;
window.renderSalesWorkspaceV110=async function(...args){const out=await _renderSalesWorkspaceV123.apply(this,args),s=await refreshCashStatusV123('secretaria');const launch=document.querySelector('.sales-launch-v120');if(launch)launch.insertAdjacentHTML('afterend',cashStatusFlagHtmlV123(s.session,s.point,s.shift));return out};
window.renderVendas=function(){ensureSaleStateV110(true);return renderSalesWorkspaceV110()};
const _startSaleWizardV123=window.startSaleWizardV120;
window.startSaleWizardV120=async function(...args){await refreshCashStatusV123('secretaria');return _startSaleWizardV123.apply(this,args)};
const _wizardPaymentsHtmlV123=window.wizardPaymentsHtmlV120;
window.wizardPaymentsHtmlV120=function(){const html=_wizardPaymentsHtmlV123();if(state.cashStatusV123?.session)return html;return html.replace('class="choice-card-v120" onclick="openPaymentV110(\'dinheiro\')"','class="choice-card-v120 cash-lock-v123" onclick="openPaymentV110(\'dinheiro\')"').replace('<strong>Dinheiro</strong><span>Calcula troco e movimenta o caixa físico.</span>','<strong>Dinheiro 🔒</strong><span>Abra e confira o caixa físico antes de receber.</span>')};
const _confirmPaymentV123=window.confirmPaymentV110;
window.confirmPaymentV110=async function(...args){const method=$('#v110PayMethod')?.value;if(method==='dinheiro'){const s=await refreshCashStatusV123('secretaria');if(!s.session){appMessage('O caixa físico não está aberto. Abra e confira o caixa antes de adicionar pagamento em dinheiro.');return}}return _confirmPaymentV123.apply(this,args)};
const _openPaymentV123=window.openPaymentV110;
window.openPaymentV110=async function(method){
  const s=await refreshCashStatusV123('secretaria'),explicit=method!=null,chosen=explicit?method:(s.session?'dinheiro':'pix');if(chosen==='dinheiro'&&!s.session){if(await appConfirm('O caixa físico ainda não foi aberto. Vendas em dinheiro estão bloqueadas.',{title:'Abrir o caixa agora?',confirmLabel:'Abrir caixa',cancelLabel:'Voltar'}))await openCash('secretaria',s.shift);return}
  return _openPaymentV123(chosen)
};

/* Flag e botão de dinheiro na cantina. */
const _renderAtendimentoV123=window.renderAtendimento;
window.renderAtendimento=async function(...args){const out=await _renderAtendimentoV123.apply(this,args),s=await refreshCashStatusV123('cantina');const host=$('#mainContent'),grid=host?.querySelector('.grid.g2');if(grid)grid.insertAdjacentHTML('beforebegin',cashStatusFlagHtmlV123(s.session,s.point,s.shift));applyCashCartLockV123();return out};
const _renderCashCartV123=window.renderCashCart;
window.renderCashCart=function(...args){const out=_renderCashCartV123.apply(this,args);applyCashCartLockV123();return out};
function applyCashCartLockV123(){const btn=document.querySelector('#cashCart button[onclick="registerCashSale()"]');if(!btn)return;const open=!!state.cashStatusV123?.session;btn.disabled=!open;btn.classList.toggle('cash-lock-v123',!open);btn.textContent=open?'Confirmar venda em dinheiro':'Abra o caixa para vender em dinheiro'}

/* Reforço final: qualquer venda com dinheiro valida sessão aberta na hora da gravação. */
const _registerCashSaleV123=window.registerCashSale;
window.registerCashSale=async function(...args){try{await ensureCashSession('cantina');return await _registerCashSaleV123.apply(this,args)}catch(e){appMessage(e.message)}};
const _saveStructuredSaleV123=window.saveStructuredSaleV110;
window.saveStructuredSaleV110=async function(...args){const st=ensureSaleStateV110(),hasCash=st.payments.some(p=>p.metodo==='dinheiro'&&Number(p.valorAplicadoCentavos||0)>0);if(hasCash){try{await ensureCashSession('secretaria')}catch(e){appMessage(e.message);return}}return _saveStructuredSaleV123.apply(this,args)};

/* Relatório identifica a sessão para não misturar vários fechamentos do mesmo turno. */
window.downloadCashPdfV110=async function(){
  const r=state.currentCashReportV110;if(!r?.cash)return;const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'}),c=r.cash,sessionTitle=c.numeroSessao?`${cashSessionLabelV123(c)} · `:'';let y=await drawPdfBrandHeaderV121(pdf,'Fechamento de caixa',`${sessionTitle}${cashPointLabelV121(r.point)} · ${cashShiftLabelV121(r.shift)} · ${c.dataChave||dateKey()}`);
  const lines=[['Saldo inicial',r.initial],['Vendas em dinheiro',r.sales],['Saldo esperado',c.valorEsperadoRegistradoCentavos??r.expected],['Saldo contado',c.valorContadoCentavos],['Diferença',c.diferencaCentavos]];pdf.setTextColor(30);pdf.setFontSize(10);for(const [label,val] of lines){if(val==null)continue;pdf.setDrawColor(225);pdf.line(15,y+6,195,y+6);pdf.setFont('helvetica','normal');pdf.text(label,17,y+4);pdf.setFont('helvetica','bold');pdf.text(fmt(val).replace(/0/g,' '),193,y+4,{align:'right'});y+=9}
  y+=6;pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.text('FECHAMENTO E RESPONSABILIDADE',15,y);y+=7;pdf.setTextColor(30);pdf.setFont('helvetica','normal');if(c.numeroSessao){pdf.text(`Sessão: ${cashSessionLabelV123(c)}`,17,y);y+=5}pdf.text(`Aberto por: ${c.abertoPorNome||c.operadorNome||c.operadorId||'-'}`,17,y);y+=5;pdf.text(`Assinatura operacional: ${c.fechadoPorNome||c.assinaturaOperacional?.nome||'-'}`,17,y);y+=5;pdf.text(`Fechado em: ${c.fechadoEm?humanDate(c.fechadoEm):'-'}`,17,y);y+=7;if(Number(c.diferencaCentavos||0)!==0){pdf.setFillColor(255,248,236);const just=pdf.splitTextToSize(`Justificativa da divergência: ${c.justificativaDivergencia||'Não informada'}`,172),h=just.length*4.5+8;pdf.roundedRect(15,y,180,h,2,2,'F');pdf.setTextColor(110,72,15);pdf.text(just,19,y+6);y+=h+7}
  pdf.setTextColor(44,56,150);pdf.setFont('helvetica','bold');pdf.text('MOVIMENTOS',15,y);y+=7;pdf.setTextColor(30);pdf.setFont('helvetica','normal');for(const m of [...(r.moves||[])].sort((a,b)=>String(a.criadoEm).localeCompare(String(b.criadoEm)))){if(y>274){pdf.addPage();y=await drawPdfContinuationHeaderV121(pdf,'Fechamento de caixa')}pdf.setFontSize(8.5);pdf.text(humanDate(m.criadoEm),15,y);pdf.text(pdf.splitTextToSize(String(m.tipo||'').replaceAll('_',' '),62),55,y);pdf.text(fmt(m.valorCentavos).replace(/0/g,' '),193,y,{align:'right'});y+=6}
  const suffix=c.numeroSessao?`-sessao-${String(c.numeroSessao).padStart(3,'0')}`:'';pdf.save(`fechamento-caixa-${r.point}-${c.dataChave||dateKey()}${suffix}.pdf`)
};

/* Atualiza versão sem apagar histórico. */
/* atualização de versão herdada removida pela V1.5.0-dev2 */
