const {initFirebase,json,parseBody,nowIso}=require('./_utils');
const {verifyStaff,cpfHash,normalizeCpf}=require('./_family-utils');
const BASE=require('./_base-oficial-2026');

const CLEAR_COLLECTIONS=[
 'alertas','caixas','contas_alunos','dados_pagamento_responsavel','disponibilidade_salgados','eventos_checkout_infinitepay','fechamentos_caixa','fechamentos_cantina','fechamentos_semanais','fila_integracao','historico_auditoria','itens_venda','movimentos_caixa','movimentos_conta','movimentos_estoque','notificacoes','ocorrencias_entrega','pagamentos','pagamentos_checkout','pagamentos_venda','pedidos','pedidos_farda','pedidos_operacionais','sessoes_caixa','periodos_responsabilidade_caixa','divergencias_caixa','ocorrencias_caixa','solicitacoes_correcao_pedido','taxas_pagamento','tentativas_checkout','tentativas_confirmacao_saldo','transacoes_infinitepay','transferencias_caixa','vendas','vendas_online_links','solicitacoes_reset_responsavel','reset_senha_responsavel','responsaveis_acesso','ativacoes_meu_piaget','sessoes_meu_piaget'
];
const PRESERVED_LABELS=['alunos e matrículas','responsáveis e vínculos','catálogo','preços e estoques atuais','configurações','usuários da equipe'];
function accountSplit(net){net=Math.round(Number(net||0));return{saldoContaCentavos:net,saldoCreditoCentavos:Math.max(0,net),dividaCentavos:Math.max(0,-net)}}
async function commitChunks(db,ops,max=420){for(let i=0;i<ops.length;i+=max){const batch=db.batch();for(const op of ops.slice(i,i+max)){if(op.kind==='set')batch.set(op.ref,op.data,op.options||{merge:true});else if(op.kind==='delete')batch.delete(op.ref)}await batch.commit()}}
async function countCollection(db,name){const s=await db.collection(name).get();return s.size}
async function prepareBase(db,staff){const now=nowIso(),cfgSnap=await db.collection('configuracoes').doc('sistema').get(),cfg=cfgSnap.exists?cfgSnap.data():{},baseLimit=Number(cfg.limiteMaximoFiadoCentavos||5000),officialStudentIds=new Set(BASE.alunos.map(x=>x.id)),ops=[];
 const currentStudents=await db.collection('alunos').get();for(const d of currentStudents.docs){if(!officialStudentIds.has(d.id))ops.push({kind:'set',ref:d.ref,data:{ativo:false,statusAluno:'inativo_base_2026',atualizadoEm:now},options:{merge:true}})}
 const counts=new Map();for(const l of BASE.vinculos)counts.set(l.responsavelId,(counts.get(l.responsavelId)||0)+1);
 const currentFamilyAccounts=await db.collection('contas_responsaveis').get().catch(()=>({docs:[]})),accountIds=new Set(currentFamilyAccounts.docs.map(d=>d.id));
 const currentResponsibles=await db.collection('responsaveis_financeiros').get().catch(()=>({docs:[]})),responsibleById=new Map(currentResponsibles.docs.map(d=>[d.id,d.data()||{}]));
 /* Na preparação (antes do marco zero), preservar o saldo de teste existente.
    Para famílias com irmãos, a nova conta nasce com a soma líquida das contas
    antigas dos alunos. O Marco Zero é a única ação que zera esses valores. */
 const legacyAccounts=await db.collection('contas_alunos').get().catch(()=>({docs:[]})),legacyByStudent=new Map(legacyAccounts.docs.map(d=>[d.id,d.data()||{}]));
 const studentsByResponsible=new Map();for(const v of BASE.vinculos){if(!studentsByResponsible.has(v.responsavelId))studentsByResponsible.set(v.responsavelId,[]);studentsByResponsible.get(v.responsavelId).push(v.alunoId)}
 for(const r of BASE.responsaveis){const data={...r,quantidadeAlunosAtivos:counts.get(r.id)||0,atualizadoEm:now};if(!r.cpfHash){const existing=responsibleById.get(r.id)||{};delete data.cpfHash;delete data.cpfFinal;if(existing.cpfValido===true&&existing.cpfHash){delete data.cpfValido;}else{data.cpfValido=false;data.cpfFinal='';}}ops.push({kind:'set',ref:db.collection('responsaveis_financeiros').doc(r.id),data,options:{merge:true}});const accRef=db.collection('contas_responsaveis').doc(r.id),max=baseLimit*(counts.get(r.id)||1);if(accountIds.has(r.id))ops.push({kind:'set',ref:accRef,data:{responsavelId:r.id,quantidadeAlunosAtivos:counts.get(r.id)||0,limiteBasePorAlunoCentavos:baseLimit,limiteMaximoFamiliaCentavos:max,atualizadoEm:now},options:{merge:true}});else{const legacy=(studentsByResponsible.get(r.id)||[]).map(id=>legacyByStudent.get(id)).filter(Boolean),net=legacy.reduce((sum,a)=>sum+Number(a.saldoContaCentavos??(Number(a.saldoCreditoCentavos||0)-Number(a.dividaCentavos||0))),0),legacyLimit=Math.min(max,legacy.reduce((sum,a)=>sum+Math.max(0,Number(a.limiteFiadoCentavos||0)),0));ops.push({kind:'set',ref:accRef,data:{responsavelId:r.id,quantidadeAlunosAtivos:counts.get(r.id)||0,limiteBasePorAlunoCentavos:baseLimit,limiteMaximoFamiliaCentavos:max,limiteFiadoCentavos:legacyLimit,autorizadoSemSaldo:legacy.some(a=>Boolean(a.autorizadoSemSaldo)),bloqueioManual:legacy.some(a=>Boolean(a.bloqueioManual)),bloqueadoPorLimite:legacy.some(a=>Boolean(a.bloqueadoPorLimite)),bloqueioSaldoSemanal:legacy.some(a=>Boolean(a.bloqueioSaldoSemanal)),...accountSplit(net),migradoDeContasAlunos:true,criadoEm:now,atualizadoEm:now},options:{merge:true}})}}
 const officialClasses=new Map();for(const a of BASE.alunos){if(!officialClasses.has(a.turmaId))officialClasses.set(a.turmaId,{id:a.turmaId,nome:a.turma,ordem:a.ordemTurma,turno:a.turno,grupoRecreio:a.grupoRecreio,recreioInicio:a.recreioInicio,recreioFim:a.recreioFim,anoLetivo:2026,ativo:true,origem:'SIGA 07/08/2026',atualizadoEm:now})}
 for(const t of officialClasses.values())ops.push({kind:'set',ref:db.collection('turmas').doc(t.id),data:t,options:{merge:true}});
 for(const a of BASE.alunos){ops.push({kind:'set',ref:db.collection('alunos').doc(a.id),data:{...a,atualizadoEm:now},options:{merge:true}});ops.push({kind:'set',ref:db.collection('matriculas_ano').doc(`${a.id}_2026`),data:{id:`${a.id}_2026`,alunoId:a.id,matricula:a.matricula,anoLetivo:2026,turma:a.turma,turmaId:a.turmaId,turmaOriginal:a.turmaOriginal,turno:a.turno,status:'cursando',ativo:true,origem:'SIGA 07/08/2026',atualizadoEm:now},options:{merge:true}})}
 for(const v of BASE.vinculos)ops.push({kind:'set',ref:db.collection('vinculos_responsavel_aluno').doc(v.id),data:{...v,atualizadoEm:now},options:{merge:true}});
 ops.push({kind:'set',ref:db.collection('configuracoes').doc('sistema'),data:{versao:'1.6.0-rc2.7-meu-piaget-familias',anoLetivoAtual:2026,modeloContaFinanceira:'responsavel',meuPiagetAtivo:true,baseOficial2026Preparada:true,baseOficial2026PreparadaEm:now,baseOficial2026PreparadaPorId:staff.id,baseOficial2026PreparadaPorNome:staff.nome,urlMeuPiaget:'/meu-piaget.html',urlEquipe:'/equipe.html',atualizadoEm:now},options:{merge:true}});
 await commitChunks(db,ops);return{alunos:BASE.meta.alunos,responsaveis:BASE.meta.responsaveis,vinculos:BASE.meta.vinculos,cpfPendentes:BASE.meta.responsaveisCpfInvalido};}
async function status(db){const cfg=await db.collection('configuracoes').doc('sistema').get(),invalid=await db.collection('responsaveis_financeiros').where('cpfValido','==',false).get().catch(()=>({docs:[]})),marco=await db.collection('marcos_operacao').doc('operacao_oficial').get().catch(()=>null);return{base:BASE.meta,preparada:Boolean(cfg.exists&&cfg.data()?.baseOficial2026Preparada),operacaoOficial:Boolean(marco?.exists),marco:marco?.exists?marco.data():null,cpfPendentes:invalid.docs.map(d=>({id:d.id,nome:d.data()?.nome||'Responsável',cpfFinal:d.data()?.cpfFinal||''}))}}
async function previewReset(db){const counts={};let total=0;for(const c of CLEAR_COLLECTIONS){const n=await countCollection(db,c).catch(()=>0);counts[c]=n;total+=n}return{totalDocumentos:total,colecoes:counts,preservado:PRESERVED_LABELS,baseOficial:{alunos:BASE.meta.alunos,responsaveis:BASE.meta.responsaveis}}}
async function backupAndClear(db,staff){const backupId=`implantacao_${Date.now()}`,root=db.collection('backups_implantacao').doc(backupId),created=nowIso();await root.set({id:backupId,tipo:'pre_operacao_oficial',criadoEm:created,criadoPorId:staff.id,criadoPorNome:staff.nome,colecoes:CLEAR_COLLECTIONS,status:'em_andamento'});let total=0;for(const name of CLEAR_COLLECTIONS){const snap=await db.collection(name).get();if(!snap.size)continue;const ops=[];for(const d of snap.docs){const safeId=`${name}__${Buffer.from(d.id).toString('base64url')}`;ops.push({kind:'set',ref:root.collection('documentos').doc(safeId),data:{colecao:name,documentoId:d.id,dados:d.data()},options:{merge:false}});ops.push({kind:'delete',ref:d.ref});total++}await commitChunks(db,ops,380)}await root.set({status:'concluido',documentos:total,concluidoEm:nowIso()},{merge:true});return{backupId,total}}
async function zeroFamilyAccounts(db){const cfg=await db.collection('configuracoes').doc('sistema').get(),base=Number(cfg.data()?.limiteMaximoFiadoCentavos||5000),rs=await db.collection('responsaveis_financeiros').get(),ops=[];for(const d of rs.docs){const r=d.data()||{},count=Math.max(1,Number(r.quantidadeAlunosAtivos||1));ops.push({kind:'set',ref:db.collection('contas_responsaveis').doc(d.id),data:{responsavelId:d.id,quantidadeAlunosAtivos:Number(r.quantidadeAlunosAtivos||0),limiteBasePorAlunoCentavos:base,limiteMaximoFamiliaCentavos:base*count,limiteFiadoCentavos:0,autorizadoSemSaldo:false,bloqueioManual:false,bloqueadoPorLimite:false,bloqueioSaldoSemanal:false,...accountSplit(0),atualizadoEm:nowIso()},options:{merge:true}})}await commitChunks(db,ops)}
module.exports=async(req,res)=>{if(req.method!=='POST')return json(res,405,{error:'Método não permitido.'});const db=initFirebase(),b=parseBody(req);try{const staff=await verifyStaff(db,req,['admin','gestao']),acao=String(b.acao||'');if(acao==='status')return json(res,200,{ok:true,...await status(db)});if(acao==='preparar_base')return json(res,200,{ok:true,...await prepareBase(db,staff),...await status(db)});if(acao==='preview_reset')return json(res,200,{ok:true,...await previewReset(db)});if(acao==='iniciar_operacao'){
 if(String(b.confirmacao||'').trim()!=='INICIAR OPERAÇÃO REAL')return json(res,400,{error:'Digite exatamente INICIAR OPERAÇÃO REAL para confirmar.'});const current=await status(db);if(!current.preparada)return json(res,409,{error:'Prepare a base oficial de alunos e responsáveis antes do marco zero.'});if(current.cpfPendentes.length)return json(res,409,{error:'Existe responsável com CPF pendente. Corrija antes de iniciar a operação oficial.',cpfPendentes:current.cpfPendentes});if(current.operacaoOficial)return json(res,409,{error:'A operação oficial já foi iniciada e não pode ser zerada novamente por este fluxo.'});const backup=await backupAndClear(db,staff);await zeroFamilyAccounts(db);const now=nowIso(),marco={id:'operacao_oficial',inicioEm:now,anoLetivo:2026,backupId:backup.backupId,criadoPorId:staff.id,criadoPorNome:staff.nome,baseAlunos:BASE.meta.alunos,baseResponsaveis:BASE.meta.responsaveis};await db.collection('marcos_operacao').doc('operacao_oficial').set(marco);await db.collection('configuracoes').doc('sistema').set({operacaoOficialInicioEm:now,operacaoOficialBackupId:backup.backupId,atualizadoEm:now},{merge:true});await db.collection('historico_auditoria').add({acao:'operacao_oficial_iniciada',tituloHumano:'Operação oficial iniciada',descricaoHumana:`O sistema iniciou a operação oficial com ${BASE.meta.alunos} alunos ativos e ${BASE.meta.responsaveis} responsáveis financeiros.`,usuarioId:staff.id,usuarioNome:staff.nome,usuarioPerfil:staff.perfil,criadoEm:now,versao:'1.6.0-rc2.7-meu-piaget-familias'});return json(res,200,{ok:true,marco,backup});}
 return json(res,400,{error:'Ação inválida.'});}catch(e){console.error('implantacao',e);return json(res,e.status||500,{error:e.message||'Não foi possível concluir a operação.'})}};
